### ISSUE TITLE
Comparing a `1.x` version results in being lower than `1.1`

### ISSUE THREAD

**Issue by ChampionAsh5357** [readthedocs/readthedocs.org#10046]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mcforge/

## Expected Result

The version warning banner should not show up when the latest branch is being viewed using the `latest` or branch name (for our specific case, `1.19.x`) identifier. 

## Actual Result

When viewing the site through the [`latest` identifier](https://docs.minecraftforge.net/en/latest/), the version warning message does not show up. However, when viewing through the [branch name](https://docs.minecraftforge.net/en/1.19.x/) (which should be the same as latest according to the [version list](https://readthedocs.org/projects/mcforge/versions/)), the version warning banner shows up redirecting to a different branch.

I suspect this is an issue with [footer_views.get_version_compare_data](https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/api/v2/views/footer_views.py#L30) as there is no check to see whether the current branch name is set to either the latest or stable. As such, our `1.19.x` branch, while being considered the latest, is not the highest version. For the specifics on this `1.19.x` is treated as `1.19.0`, so the branch which is considered the latest, `1.19.2`, would be considered the higher version.

**Comment by stsewd** [comment]
Hi, this is because we use semver to compare the versions, but additionally, we support the `.x` convention, we do this by simply replacing the `.x` with a `.0`

https://github.com/readthedocs/readthedocs.org/blob/d6f8e5f5191fa82d1081523bfd91ddbf4eb06c95/readthedocs/projects/version_handling.py#L44-L44

So if you have another version like `1.19.2`, then that is greater than `1.19.x`, I think we should find a way to set that as the maximum version, maybe use `.9999` instead of `.x` could be a quick solution.

**Comment by humitos** [comment]
> I think we should find a way to set that as the maximum version, maybe use `.9999` instead of `.x` could be a quick solution.

Yeah, probably replacing `.x` by `.9999` is better than replacing it by `.0` 👍🏼
