### ISSUE TITLE
Bad Request when navigating to non-canonical URL with underscores.

### ISSUE THREAD

**Issue by domdfcoding** [readthedocs/readthedocs.org#10237]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/domdf-python-tools/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/domdfcoding/

## Expected Result

Navigating to `domdf_python_tools.readthedocs.io` redirects to `domdf-python-tools.readthedocs.io`

## Actual Result

The error "Bad Request (400)" is displayed.

This was working as recently as the April 3rd. It's not limited to `domdf_python_tools` but happens for any project with an underscore or hyphen in its name.

**Comment by stsewd** [comment]
Hi, underscores on project's slugs aren't allowed, this is since that's an invalid character to be used as a subdomain. We used to have a rule at the Cloudflare level that did the redirect, but that rule was colliding with other things, so we removed it, please use `domdf-python-tools.readthedocs.io` when linking to your documentation (we always link to the correct subdomain from https://readthedocs.org/projects/domdf-python-tools/).
