### ISSUE TITLE
Search: Only use generic parsers

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#10272]
Since #10128 removed specific Sphinx domain logic in the `SphinxParser`, we aren't doing much more search indexing that's specific for Sphinx or MkDocs.

* [x] Make `SphinxParser` redundant (move anything essential into the `GenericParser`)
* [x] Make `MkDocsParser` redundant (move anything essential into the `GenericParser`)
* [x] Remove entire `readthedocs.sphinx_domains` application?
* [x] Backup and delete database table (ops)

CC: @stsewd does this list look good? Perhaps we can break into separate issues/PRs if any change becomes too complex.

**Comment by stsewd** [comment]
Looks good. Not sure if we need to back up the tables, since we aren't using them anymore, but not strong opinion about not doing it.

We should also check if we can remove the generation of the `readthedocs-sphinx-domain-names.json` file from our sphinx extension and the fjson files too.

https://github.com/readthedocs/readthedocs.org/blob/40d21dc6cc9378b4cd6d274f02d043c01da510da/readthedocs/projects/tasks/search.py#L145-L145

https://github.com/readthedocs/readthedocs-sphinx-ext/blob/a46f5ca05c7c8ec7ec30b44cc724ac334ce91a38/readthedocs_ext/readthedocs.py#L198

https://github.com/readthedocs/readthedocs-sphinx-ext/blob/f1145b1819458643f442b21083b3397aeebc8e72/readthedocs_ext/readthedocs.py#L280-L280

**Comment by humitos** [comment]
> We should also check if we can remove the generation of the `readthedocs-sphinx-domain-names.json` file from our sphinx extension and the fjson files too.

💯 , this will speed up the build time a little bit. I'm 👍🏼 on removing it if possible.

**Comment by humitos** [comment]
It would be awesome to return to this work and finish this project (cc @ericholscher). The work on this issue will allow us to use always the same parser without matter the doctool the user is using (which will give them the exact same search experience). We are pretty close now! I arrived here while doing the cleanup of the feature flags at #9779 

Remember to remove the `INDEX_FROM_HTML_FILES` as well when doing this work. It won't be required anymore, since everybody will be indexing from HTML files.

**Comment by humitos** [comment]
While reviewing https://github.com/readthedocs/readthedocs.org/pull/10042 I found the work from this issue is, in part, required to removed the `Version.documentation_type` attribute.

**Comment by ericholscher** [comment]
We're slowly rolling this out via feature flag 👍
