### ISSUE TITLE
Unable to build `latest` version from a tag

### ISSUE THREAD

**Issue by davfsa** [readthedocs/readthedocs.org#10735]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/hikari-py
* Build URL (if applicable): https://readthedocs.org/projects/hikari-py/builds/21916140/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/davfsa

## Expected Result

Documentation is properly built, as it used to be the case.

_I unfortunately haven't made a release in months, so I only noticed this recently. I could not find any git commits that could be linked to this apart from maybe [this code](https://github.com/readthedocs/readthedocs.org/pull/10606/files#diff-7e3f0077dd62ed25ce9cf092b4304af5751d48727dc572e219b63d16a88a6edbR120-R121), but this definitely used to work_

## Actual Result

Unable to build `latest` from a tag, as it fails at checkout

**Comment by stsewd** [comment]
ha! Looks like we always expect latest to be a branch (even the option is called "Default branch"), but we aren't enforcing it

https://github.com/readthedocs/readthedocs.org/blob/53e21bb3ee8a5fce0194eb5481fd81ac87d3d1fa/readthedocs/projects/forms.py#L272-L279

We are given users the option to select a tag!

This was working previously because we were treating tags and branches kind of the same, but we aren't doing that anymore.

Not sure about the fix here, probably more users were relying on us allowing latest to be a tag...

**Comment by stsewd** [comment]
I'll check tomorrow if this can be fixed, so our code accepts both, tags and branches as latest.

**Comment by stsewd** [comment]
The fix was released today, latest can now point to a tag again.

https://readthedocs.org/projects/hikari-py/builds/22038735/
