### ISSUE TITLE
[UX] French "Build version" button translation is confusing

### ISSUE THREAD

**Issue by Zeitsperre** [readthedocs/readthedocs.org#10743]
## Details

* Read the Docs project URL: Affects everyone everywhere

This bug was brought up in my team and threw a few of my Francophone colleagues for a loop.

The meaning of the "Build Version" button is too ambiguous to be translated automatically:

![image](https://github.com/readthedocs/readthedocs.org/assets/10819524/903ff628-41ae-4a40-a499-a86f4ff442d1)

For English speakers, it's safe to assume that the meaning here is "Build" is an action one can perform, whereas with

![image](https://github.com/readthedocs/readthedocs.org/assets/10819524/2df86638-369e-4e8e-a4d7-9d1d4b3a8c65)

This directly translates back to "Number of build", obscuring the meaning entirely.

An alternative I'd propose is: "Compiler une version", as that's much clearer.

**Comment by Geeyun-JY3** [comment]
I think you can fix this at [Transifex](https://explore.transifex.com/readthedocs/readthedocs/) if this is really a translation issue: https://dev.readthedocs.io/en/latest/contribute.html#contributing-to-translations
But you may need to coordinate with the reviewers or coordinators of French (fr) since most translated strings of French (fr) are reviewed.

**Comment by humitos** [comment]
Thanks for reporting this. As @Geeyun-JY3 said, all the issues related to translations are managed in Transifex; please continue the conversation there.
