### ISSUE TITLE
Version warning is disabled but "This may be an old version of this documentation"

### ISSUE THREAD

**Issue by buhtz** [readthedocs/readthedocs.org#10775]
It is new to me having this two boxes flying over my documentation. There is this "This may be an old version..." box on top and the black "v:develop" box on the bottom right.
![image](https://github.com/readthedocs/readthedocs.org/assets/11861496/d554888a-356c-4159-9221-b078d5a83861)

I would like to get rid of them. I don't want to see them and I don't need them.
I deactivated the version warning in the admin settings and rebuild the docu.
![image](https://github.com/readthedocs/readthedocs.org/assets/11861496/ba50b820-dc4b-4330-8216-a093dcd3a8fb)

But the problem persist.

**Comment by stsewd** [comment]
Hi, this is because your project is using the `build.commands` feature (beta). That feature makes use of our new flyout implementation (https://github.com/readthedocs/addons/).

We are planning on exposing the options to disable each component, for now, we can disable them on request. I have disabled the version warning, if you want us to disable the menu, let us know.

**Comment by buhtz** [comment]
Thanks a lot. Yes please also disable the menu. I never understood its purpose. ;)

**Comment by stsewd** [comment]
>  I never understood its purpose

It's used so your users can find a way back to your project on RTD, builds, downloads, switch versions, search and more.

I have disabled this feature for your project.
