### ISSUE TITLE
.readthedocs.yaml file not found during build

### ISSUE THREAD

**Issue by susannasiebert** [readthedocs/readthedocs.org#10824]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/vatools/
* Build URL (if applicable): https://readthedocs.org/projects/vatools/builds/22245396/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/susannasiebert/

## Expected Result

I added a .readthedocs.yaml configuration file to my project but am still getting the following error: 
> The configuration file required to build documentation is missing from your project. Add a configuration file to your project to make it build successfully. Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html

The config file can be found [here](https://github.com/griffithlab/VAtools/blob/master/.readthedocs.yaml).

## Actual Result

Project should build successfully.

**Comment by stsewd** [comment]
Hi, this is because you have another RTD config file in your repo https://github.com/griffithlab/VAtools/blob/master/readthedocs.yml, please delete that one, so the other one can be used.

We are tracking providing a better error message for this at https://github.com/readthedocs/readthedocs.org/issues/10502.
