### ISSUE TITLE
Duplicated search results

### ISSUE THREAD

**Issue by alonmr** [readthedocs/readthedocs.org#10911]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mlrun/
* Build URL (if applicable): https://readthedocs.org/projects/mlrun/builds/22604419/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/alonmr/

## Expected Result

Each search result to appear once.

## Actual Result

Each search result is duplicated 9 times. The number of duplications vary between the versions, some duplicate 3 times, other 9-7 others not at all.
I couldn't find anything that changed that could cause this.
Here is to config file - https://github.com/mlrun/mlrun/blob/development/.readthedocs.yml
Note we recently upgraded to sphinx 6.x thinking it would resolve the issue but the issue remains (then I learned that you override the sphinx search).

Example search with duplicated results:
https://docs.mlrun.org/en/latest/search.html?q=requirements

**Comment by stsewd** [comment]
Hi, looks like indexing is timing out for your project, so previous indexed files aren't being removed. I'm taking a look at this...

**Comment by stsewd** [comment]
Looks like this file https://docs.mlrun.org/en/latest/tutorials/colab/01-mlrun-basics-colab.html is the main problem, the HTML tags aren't balanced correctly, leading to our parser to parse past the main content and include all that js, generating a big document that ES times out while indexing.

![bad-content](https://github.com/readthedocs/readthedocs.org/assets/4975310/3498ede5-14dd-4be3-86aa-6c885f0b7314)

From your side, you can:

- Fix that file so all of its tags are closed correctly
- Ignore that file from search, see https://docs.readthedocs.io/en/stable/config-file/v2.html#search-ignore

From our side, we can:

- Reduce the number of documents we index at the same time. Instead of trying to index all 250 pages at the same time, we can index 25 at the time or similar.
- Identify documents that have broken tags, and skip them, maybe notify users somehow. Not sure if this is possible with the library we are using.
- Increase the timeout limit?

**Comment by humitos** [comment]
> Identify documents that have broken tags, and skip them, maybe notify users somehow. Not sure if this is possible with the library we are using.

Avoid parsing invalid documents looks 💯 as a first step. We can maybe add a small notification once we have implemented #10598

**Comment by alonmr** [comment]
Thanks @stsewd for the quick response.
It looks like it was fixed without us changing the mentioned html (https://docs.mlrun.org/en/latest/tutorials/colab/01-mlrun-basics-colab.html). When I'm inspecting the file it seems that all of the tags are closed correctly. If the issue returns I will try your suggestions.

**Comment by stsewd** [comment]
> It looks like it was fixed without us changing the mentioned html 

@alonmr I manually did a reindex on your version by reducing the number of documents indexed at the same time, the problem will be back once you re-build your docs.

**Comment by stsewd** [comment]
> Identify documents that have broken tags, and skip them, maybe notify users somehow. Not sure if this is possible with the library we are using.

The library we use doesn't support this. We could do the validation manually, but HTML is weird, and has lots of cases where an implicit close tag is valid... Don't think this is worth the effort.
