### ISSUE TITLE
Version Warning pop up broken due to suffix added to URL

### ISSUE THREAD

**Issue by aanm** [readthedocs/readthedocs.org#10937]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/cilium/
* Build URL (if applicable): https://readthedocs.org/projects/cilium/builds/22700191/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/aanm/

## Expected Result

The pop warning to show up on older release versions

## Actual Result

Nothing shows up.

This is due to the fact that all URLs have a `v=<random string>` suffixed to them. This breaks some integrations, namely versionwarning (cc @humitos) to work as expected.

To replicate open https://docs.cilium.io/en/v1.13 in developer mode.

See the requests performed:
![image](https://github.com/readthedocs/readthedocs.org/assets/5714066/01cd5856-615b-4908-8ff5-6cce11d46adb)

Versionwarning uses this as the "base" URL but it fails:

![image](https://github.com/readthedocs/readthedocs.org/assets/5714066/45ba486c-b38c-4674-a94f-14e7fb3c1405)

I tried to fix it up with redirects but I believe it doesn't seem to work due to the `?` in the URL.

All versions that haven't been rebuilt for a long time seem to be working, for example https://docs.cilium.io/en/v1.11/

**Comment by humitos** [comment]
Hi @aanm! It seems you are using the extension `sphinx-version-warning` (https://github.com/humitos/sphinx-version-warning/). That extension is not compatible with the latest versions of Sphinx that adds `v=` to its static files, unfortunately.

You can report the issue there if you want, but it's worth to note that I'm not actively working on that extension anymore since it's been fully replaced by the new beta Read the Docs Addons (https://github.com/readthedocs/addons) that implements a simple warning (among others features) that is shown on `latest` and `non-stable` versions to warn users when reading these versions.

If you want to give it a try in your project you can

1. go to https://beta.readthedocs.org/ (the new beta dashboard)
2. go to admin tab
3. click on addons (beta)
4. mark the checkbox to enable it and
5. save

Please, let me know if you have any feedback.

**Comment by aanm** [comment]
> Hi @aanm! It seems you are using the extension `sphinx-version-warning` (https://github.com/humitos/sphinx-version-warning/). That extension is not compatible with the latest versions of Sphinx that adds `v=` to its static files, unfortunately.
> 
> You can report the issue there if you want, but it's worth to note that I'm not actively working on that extension anymore since it's been fully replaced by the new beta Read the Docs Addons (https://github.com/readthedocs/addons) that implements a simple warning (among others features) that is shown on `latest` and `non-stable` versions to warn users when reading these versions.
> 
> If you want to give it a try in your project you can
> 
> 1. go to https://beta.readthedocs.org/ (the new beta dashboard)
> 2. go to admin tab
> 3. click on addons (beta)
> 4. mark the checkbox to enable it and
> 5. save
> 
> Please, let me know if you have any feedback.

Hey @humitos, thank your for this! This looks really great! The only issue I saw was https://github.com/readthedocs/addons/issues/132 where `v1.14`, the current "stable", is showing that warning and we would want to avoid it. Besides that everything works really well.

**Comment by humitos** [comment]
@aanm awesome! 💯 That issue is in my radar, so I will jump into it sooner than later 👍🏼 . Should we close this issue now? You can subscribe to the other to keep track of any updates there.
