### ISSUE TITLE
Flyout menu not working

### ISSUE THREAD

**Issue by cosmicBboy** [readthedocs/readthedocs.org#10955]
## Details

* Read the Docs project URL: https://flyte-next.readthedocs.io/en/latest/introduction.html
* Build URL (if applicable): https://readthedocs.org/projects/flyte-next/builds/22869188/
* Read the Docs username (if applicable): nuclyde

Using the custom build commands readthedocs config key.

## Expected Result

Expecting to see the readthedocs flyout menu on the bottom right. This was showing up correctly last week, even [older builds](https://readthedocs.org/projects/flyte-next/builds/22796482/) that showed it correctly are no longer working.

![Screenshot 2023-12-15 at 2 22 33 PM](https://github.com/readthedocs/readthedocs.org/assets/2816689/b8851deb-33e9-4f4b-abba-63b1d5e7c4f9)

## Actual Result

It's blank, cannot find the inserted RTD footer flyout menu.

**Comment by humitos** [comment]
Thanks for reporting this. It's a bug in our side. The request to https://flyte-next.readthedocs.io/_/addons/?client-version=0.9.1&api-version=0 is returning 400. This is because it should include `?project-slug=flyte-next&version-slug=latest`.

They are not included in the request because the `meta` HTML element with this data are not present in the page. I'll take a deeper look to understand why this is happening.

**Comment by humitos** [comment]
@cosmicBboy I found the issue and I fixed it. It's working now. It was an issue in our Cloudflare Worker that it was not injecting the `meta` HTML elements required for this. Please, confirm if it's working as expecting.
