### ISSUE TITLE
Notifications: migrate old custom Django message notifications 

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10988]
I kept the rendering for the default Django messages in the base template. However, we need to take a deeper look at it since it used to use `django-messages-extends` for extra and custom notifications (those that can be dismissed, etc) that we are not using anymore. That means the "Mark as read" URL and others won't work anymore.

Those messages have to be split into two groups:

1. regular Django messages attached to the request
2. notifications attached to the user that can be dismissed

https://github.com/readthedocs/readthedocs.org/blob/7d1daeeee24a0e70ffcf0debd6836c02d0b36ec3/readthedocs/templates/base.html#L121-L139

We talked about this on the PR while working on this: https://github.com/readthedocs/readthedocs.org/pull/10922#discussion_r1440156594

**Comment by agjohnson** [comment]
If I understand correctly, our plan on the old dashboard should be:

- Anything left using Django messages at this point won't be changed to our new notification backend. These are form confirmations and other temporary Django messages.
- We'd keep the template logic above for standard Django messages. The template is actually still accurate for standard messages (not sticky/persistent messages from messages-extends).
- New Notification instances should use HTML similar to this template instead of separate HTML.

The new dashboard handles standard Django messages separately from sticky messages:

https://github.com/readthedocs/ext-theme/blob/bff4b4ddf645c9e5f690dd086f47602a74e7a429/readthedocsext/theme/templates/includes/utils/messages.html#L11-L45

That logic will need to be changed to:

- Iterate over `notifications` to show Notification instances. The template logic will be changed slightly to accommodate the new Message class.
- Iterate over `messages` to continue showing Django messages as toast messages. This logic doesn't change at all.

**Comment by humitos** [comment]
Yes, I understand the summary of the plan you wrote is 👍🏼 

The code will be simplified since `message.pk` won't exist anymore since there is no messages saved into the database anymore since we stopped used sticky/permanent messages via `django-messages-extends`.

Those sticky/permanent messages are now `Notification` objects attached to a particular resource. The code to render all of these does not exist yet and part of the work required for this issue.
