### ISSUE TITLE
APIv3: add `_links` field to `Notification` responses

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10982]
Currently, the `Notification` resource response does not include the `_links` field but this will be used/required by the front-end when implementing the new system. Mainly, to know what's the dismiss URL and similar actions.

https://github.com/readthedocs/readthedocs.org/blob/623190d6d7a7b1c8d6e164246803fea5af5d527b/readthedocs/api/v3/serializers.py#L63-L84

**Comment by agjohnson** [comment]
As to the question of _do we need this_, I would say these URLs are mandatory. It's best that the backend code be reused as much as possible, instead of the front end trying to recreate resolver logic based on strings alone.

I don't have a lot of input on how this happens in the API structure though. I noted somewhere that the API endpoint URL will be passed into the JS from templates either way, so it's not important to have a common API endpoint for dismissing notifications. We can just as easily PATCH a deep URL.
