### ISSUE TITLE
Import: add organization/team field first in the project creation UI

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11111]
When import a project by a User with SSO enabled, we want to show the `Organization` field first and then if the organization doesn't have SSO enabled we should show `Team` field.

https://github.com/readthedocs/readthedocs-corporate/pull/939#discussion_r440143849

**Comment by humitos** [comment]
Can you describe a little more what you have in mind here?

**Comment by agjohnson** [comment]
I think we should do this change at the underlying form, and the templates should retain just a simple `{% form|crispy %}`. We can do this with JS if needed, which was maybe the original idea, but that seems like maybe a last resort option to me.

**Comment by humitos** [comment]
Yeah, I think we originally thought this couldn't be a backend change because of "users belonging to multiple organizations". So, depending on what the organization they want to import a project to, there may be Teams or not.

The approach we could follow here is presenting an intermediary page that lists all the organizations the user belongs to (in case there is more than one), then the user selects the organization and _then_ show the actual form to import a project with/without the team fields depending on the organization the user has selected.

**Comment by agjohnson** [comment]
At this point, I think that would be my suggestion as well. First, it probably only affects core team and maybe a few other users. But this would also make the logic I added to the project create view much more explicit, as we would have a single organization to test permisisons against. We already have the organization picker UI, so we probably only need to accept the organization as a view/form argument really.

**Comment by humitos** [comment]
Yeah, and that pattern seems easier to implement and understand from a customer perspective than dealing with magic and dynamic forms.

**Comment by humitos** [comment]
I just added a project into an organization and I wasn't asked about what Team I wanted to add it to. However, the project appears under the list of projects from that organization. I'm confused because I thought the only way to relate a project to an organization was through "Teams".

Anthony found that we have a `Organization.projects.all()` relation.

Anyways, we need to let the user to select the _team_ where they want to add the project to.

Probably we need to think more about this whole UX workflow 😄

**Comment by humitos** [comment]
I thought a little more about this and made a POC locally. Basically, I added a new step in the import wizard form that ask for the `organization` upfront, and based on that it shows (via Javascript) the `team` available:

![Screenshot_2024-08-13_15-31-33](https://github.com/user-attachments/assets/3a70a20d-fbc0-4ef2-8ff7-95ce60146ef3)


This works fine and covers one of the cases we talked here. However, it doesn't work fine for users with _only one organization_ and without using SSO (most of our users, currently) because we will have an extra step in the wizard _just to select the `team`_ which I think it's too much.

I'm thinking about copying the pattern of pre-render all the available teams in Django and hide/show them via Javascript based on the organization selected. Then, if they have only one organization and they are using VCS SSO we don't show the `team` input at all.

What do you think about this approach?

**Comment by agjohnson** [comment]
Hrm. This feels like a good place to just use an API interaction, it will be a bit hacky and awkward to create a mixed application logic/JS form like you're describing -- lots of mixed Knockout bindings and field manipulations just to temporarily hide the fields you're creating.

We could consider dropping the organization field, that is mostly a secondary field for the user as we are requiring they select a team already -- organization is implicit in this. Granted, we do attach it to the organization directly, but that feels like a covert operation the user doesn't really need information on.

**Comment by humitos** [comment]
> This feels like a good place to just use an API interaction

We don't have an API endpoint to list all the teams for all the organizations. In fact, we deleted the `teams` expandable field due to security reasons in https://github.com/readthedocs/readthedocs.org/pull/11471. We currently don't have a way to get this data through the API.

> Is there a strong reason we even want multiple fields for teams?

No, we only need 1 team field. I'm creating multiple fields just as a way to separate/isolate what teams belong/are available to each of the organizations and swap them based on the organization selected.

> I think an interstitial form wizard page would be best. There are a few cases where we can skip this page -- linked directly from and org team page "Add project" button, owner has one org/team, etc.

I mentioned the reasons why I found this not working great in my previous comment. Even people with 1 organization need to select the team. So, having a whole new page just to select the team is bad UX, in my opinion.

With the current approach proposed (keeping the organization/team field in the same page) we can show/hide one or both fields based on the authentication method.

**Comment by humitos** [comment]
I like the UX pattern I'm proposing here, but I'm not sure how to continue working on this regarding the technical aspects. I will open a new PR that makes usage of search category for now and get some feedback there.

**Comment by stsewd** [comment]
> We don't have an API endpoint to list all the teams for all the organizations. In fact, we deleted the teams expandable field due to security reasons in https://github.com/readthedocs/readthedocs.org/pull/11471. We currently don't have a way to get this data through the API.

We do, a replacement was added in that same PR, https://docs.readthedocs.io/en/stable/api/v3.html#organization-teams-list.

**Comment by humitos** [comment]
Oh great! I missed that 👍

I'll update my PR to use those endpoints.

**Comment by humitos** [comment]
I'm getting confused about this and I'm not sure how to move forward here. I think our conversation will benefit from having the use cases well defined. How would be the UX (wizard steps) for the following cases?

1. the user has only one organization and is admin of a team (_most common case_)
2. the user has only one organization and is not admin of any team
3. the user has only one organization and it has VCS SSO enabled (no teams)
4. the user has multiple organizations and is admin of multiple teams
5. the user has multiple organizations and is not admin of any team
6. the user has multiple organizations and one of them has VCS SSO enabled (no teams)
7. ... _are there more cases that I may be missing?_

Could you describe the steps/wizard form for each of these cases clearly? Also, would you show the "Select organization/team" page _before_ selecting the repository?

**Comment by agjohnson** [comment]
> Could you describe the steps/wizard form for each of these cases clearly?

I don't think we should have differing forms, fields, or UX for these use cases. We should show the same single field for every use case. This keeps it easy for us to maintain and _predictable and consistent for the user_.

We can play more with skipping this field later, in another iteration. We don't skip this field for many users now, so this optimization doesn't feel like a requirement for this issue. This feels like separate work entirely.

A category search dropdown like you started to implement still seems like a good way to go. I also noted earlier that we can also accomplish this without replacing the field just yet.

I think the one thing to do here is to make this one, unified field for org and team selection. We'd need to add options for SSO organizations in the dropdown -- under each SSO organization heading a option: "Any user with permissions in this organization". Ultimately, this requires no dynamic front end fields.

Without this, _some organizations seemingly attach projects to an organization field_ and _some organizations to a team field_. We don't want this confusion, and we already sort of got confused by this ourselves.

The selection for "attach this project to an SSO organization" feels unified and consistent because it's alongside team selection UI instead of a separate, conditional organization field.

> Also, would you show the "Select organization/team" page before selecting the repository?

Yes, it feels like it should be the first step. Choosing a team for the project is low effort in comparison to automatically/manually connecting a repository. We want the user to clear the low effort bars before giving them harder work, otherwise they might just waste their time. Choosing a org/team is very likely to block a user from adding a project, repo connection is as well.

We should work on skipping/hiding this step, but that comes next iteration.

**Comment by humitos** [comment]
> I don't think we should have differing forms, fields, or UX for these use cases. We should show the same single field for every use case. This keeps it easy for us to maintain and _predictable and consistent for the user_.

Do we want a field like this one?

![Screenshot_2024-08-20_12-35-30](https://github.com/user-attachments/assets/c52f7f71-a446-40ff-ab01-afd4e60371d7)

Take a look at _all the options_ since there are considered all the auth mechanism we currently support. There should be considered all the possible scenarios, making the user to _always_ have an option to choose. The field will be _required_.

**Comment by agjohnson** [comment]
> Do we want a field like this one?

That is looking great. We can build on top of this later to communicate these are teams, show org SSO status, etc.

> Are not contemplated in the previous image, but I imagine we could show a note similar to the one when the user doesn't have an account connected using the pre-validation method for the form

For cases where we can give the user an error, a validation error will definitely be a better experience than and empty list of teams/orgs :+1: 

We already do have validation errors for some of these use cases:

https://github.com/readthedocs/readthedocs.org/blob/6b9f1a699275ce9b19cc29ff6432b61adfe0892c/readthedocs/projects/forms.py#L343-L359

These rules did note some tuning too:

https://github.com/readthedocs/readthedocs.org/blob/6b9f1a699275ce9b19cc29ff6432b61adfe0892c/readthedocs/projects/forms.py#L294-L320
