### ISSUE TITLE
Auth: add a cookie to pin user to beta instance

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11249]
On login or maybe on use of the beta dashboard, we should set a cookie or session variable to redirect the user to the beta dashboard whenever they log in. The notification links will be temporary

**Comment by humitos** [comment]
> On login or maybe on use of the beta dashboard

I think this won't work since we need the `beta=true` cookie to be on `readthedocs.org` not on the beta dashboard domain. However, I suppose that we can set the cookie when the user clicks on the notification to go to the new dashboard from the old dashboard

![Screenshot_2024-04-25_12-00-33](https://github.com/readthedocs/readthedocs.org/assets/244656/37d1b382-5056-4e32-834e-5f14cb0bdf5b)

and _remove_ when they click on the notification from the new dashboard.

![Screenshot_2024-04-25_12-01-44](https://github.com/readthedocs/readthedocs.org/assets/244656/793458c2-d525-49af-8c04-87996548c3b9)

I suppose we will need to modify that link with something like `readthedocs.org/?cookie=remove` since it's also a different domain.

**Comment by agjohnson** [comment]
From our offsite, I believe we decided to make this a profile setting instead of a cookie.

**Comment by humitos** [comment]
I think we shouldn't do this work at this point considering that we are deploying `app.` today. We probably just can make the switch and make `app.` official after a few weeks or a month from now. The new dashboard has been pretty solid lately.

**Comment by humitos** [comment]
We talked about not doing this issue and try to move more users to the new dashboard by doing other small tasks.
