### ISSUE TITLE
Stuck on Verify Your Email Address

### ISSUE THREAD

**Issue by agusmakmun** [readthedocs/readthedocs.org#11250]
## Details

I have this case:
1. My GitHub email already changed, because I have no longer use it, and unable to login the old email.
    Let say, my-old-email@mydomain.com _(the domain is no longer exist)_.
2. I have delete my-old-email@mydomain.com from GitHub emails.
3. I have deleted the readthedocs from `Authorized OAuth Apps` in GitHub.
4. When I register again using Github application:
    - it still using my-old-email@mydomain.com
    - and stuck on Verify Your Email Address
5. And I'm unable to login.

![readthedocs](https://github.com/readthedocs/readthedocs.org/assets/7134451/66190447-e9f9-4066-b75e-fe31e9a6272c)

## Expected Result

Should use the new primary email.

## Actual Result

Still using old email.

### Info

Username: agusmakmun

**Comment by stsewd** [comment]
Hi, please email us at support@readthedocs.org with the details of your account so we can mark your old email as verified, and you can continue using your old account.

The problem here is that deleting the OAuth application on GitHub doesn't delete your account on RTD, so it still has the old email linked to it (and set as primary).
