### ISSUE TITLE
Sphinx autodoc fails to import submodules, only on RTD

### ISSUE THREAD

**Issue by SGeevers** [readthedocs/readthedocs.org#11271]
Hello, for some reason, building documentation with Sphinx works fine locally, but fails on readthedocs. At the final build step, it gives warnings of the form:

> WARNING: autodoc: failed to import class 'dummy_module.dummy_class.Dummy' from module 'rtctools_simulation_modelling_extension'; the following exception was raised:
No module named 'rtctools_simulation_modelling_extension.dummy_module'

In RTD, autodoc only fails for submodules, not for classes in the main module.

I am aware of a similar issue #8622, which was caused by an import error, but I am unable to locate any import error in my project. I also created a dummy submodule without any dependencies, but this module still can't be found.

## Details

* Read the Docs project URL: https://rtc-tools-simulation-modelling-extension.readthedocs.io/en/test_readthedocs/
* Build URL (if applicable): https://readthedocs.org/projects/rtc-tools-simulation-modelling-extension/builds/24032522/
* Read the Docs username (if applicable): SjoerdGeevers

## Expected Result

Expected that autodoc works for all classes. This is the case when building the documentation locally (test with both Python 3.9 and 3.11.6).

## Actual Result

Autodoc fails, but only for classes in submodules. For classes in the main module, it works fine.

**Comment by stsewd** [comment]
Hi, looks like this is a problem with your pyproject, not RTD. In the distribution, only the top level package is being included https://gitlab.com/rtc-tools-project/rtc-tools-simulation-modelling-extension/-/blob/41a7986bbc3cdcfcf2fbf0a41b264d3c0bfb80a9/pyproject.toml#L7.

My guess as to why this works locally, is because you are probably running the build command from the project root (so Python automatically detects the packages), on RTD we call the build command from your docs directory (here Python relies on the installed package).

See https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#auto-discovery and https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html.
