### ISSUE TITLE
Version warning banners not showing

### ISSUE THREAD

**Issue by pmocz** [readthedocs/readthedocs.org#11501]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mesa_doc/

## Expected Result

I'm expecting some version banner warnings to show up as I switch versions of the project using the flyout. I have all the new add-ons enabled in read-the-docs maintainer dashboard. The project uses github tags

## Actual Result

I do not see version warning banners

**Comment by stsewd** [comment]
Hi, this is because your versions don't follow semver as specified by the PEP 440 (https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working). We use that to sort versions, and get the stable version. Since none of your versions is valid, we don't have a stable version to link to (we always link to the stable version in the warning banner).

See https://github.com/readthedocs/readthedocs.org/issues/11183 and https://github.com/readthedocs/readthedocs.org/issues/5319, for letting users define how to get the stable version.
