### ISSUE TITLE
Version selector not working in 2.1.0rc1

### ISSUE THREAD

**Issue by dylanh724** [readthedocs/readthedocs.org#11520]
I don't believe this one needs too many details: If you RTD build with 2.1.0rc1 in any scenario, your bottom-left version selector will be missing.

Just a heads up! Downgrading back to 2.0.0 fixed it.

Sphinx 7.4.7

**Comment by humitos** [comment]
Hi @dylanh724 👋🏼 . Do you have Read the Docs Addons enabled on your project? https://docs.readthedocs.io/en/stable/addons.html#enabling-read-the-docs-addons

Note that we are in the middle of a transition (https://about.readthedocs.com/blog/2024/07/addons-by-default/), and I think you are hitting the expected behavior here: no flyout with the latest rc version of the theme and without addons enabled.

Can you confirm us if it does work as expected when using `2.1.0rc1` and having the addons enabled in your project? 

> I don't believe this one needs too many details

What's the URL of your project on Read the Docs?

**Comment by dylanh724** [comment]
Hi, 

* I can confirm that in `v2.0.0`, enabling the flyout brings the version selector back (floating).
* Going back to `v2.1.0rc1` and following your guide, it now shows **both** the bottom-left version selector and the flyout:

![image](https://github.com/user-attachments/assets/3a332413-c9b3-49ef-a56b-c83fd6fa07ac)

I'm going to assume if I turn off flyout, all will be resolved (just needed that addon enabled? I would've had no clue whew).

https://docs.xsolla.cloud/en/latest/

This is the live site that has the rc1 theme with NO version selector (expected bottom-left selector), _before_ I activated the addon instructions (I haven't rebuilt).

What's interesting is that you can actually see where the bottom-left version selector is *supposed* to be. If you scroll down the sticky navbar, you can see the chunk of space reserved for it:

![GIF](https://github.com/user-attachments/assets/8391fd5b-da0f-4769-b360-1aa38b492d43)

**Comment by humitos** [comment]
> Going back to `v2.1.0rc1` and following your guide, it now shows **both** the bottom-left version selector and the flyout:

This is the expected behavior for now. We are [working on a PR](https://github.com/readthedocs/sphinx_rtd_theme/pull/1580) that will allow users to disable the flyout from the theme and only leave the addons flyout or vice-versa.

**Comment by humitos** [comment]
I'm closing this issue for now, but feel free to provide any feedback you may have and/or re-open it.
