### ISSUE TITLE
Allow me to hide ver selector + redundant search bar "On RTD" row

### ISSUE THREAD

**Issue by dylanh724** [readthedocs/readthedocs.org#11527]
## What's the problem this feature will solve?

I want to hide the version selector "On Read The Docs" row and the redundant "Search" row to prevent bloat:

![image](https://github.com/user-attachments/assets/d61979a7-a170-49f6-a72c-e3a28372f087)

## Describe the solution you'd like

* For the "On RTD" row, at first, I thought it was using cookies to detect I'm a maintainer already logged in, so injected that row in. However, in incognito, I was not pleased to see this still shows -- end users are unlikely to want to see this. 
* For the search bar, I already have a search bar at the top.

## Alternative solutions

I do not want to hide it completely -- I just want the macro version selector.

## Additional context

Ultimately, I just want this when popped out:

![image](https://github.com/user-attachments/assets/51579f46-0616-47c4-a2c3-b93b7054817a)

**Comment by humitos** [comment]
We currently don't support partial customization of the flyout. However, we expose a JavaScript `CustomEvent` that provides a JSON-like object with all the data required to generate a custom flyout with your needs. See https://github.com/readthedocs/sphinx_rtd_theme/pull/1526 as an example of the implementation of this in the Read the Docs Sphinx theme.

Unfortunately, we don't have better documentation for this approach, but we are working on writing a guide so people can integrate this data easily.

This issue is related in some way to https://github.com/readthedocs/readthedocs.org/issues/11474.

**Comment by humitos** [comment]
On the new implementation of the flyout (using addons), the "Search" input is not shown when search addons is disabled. For the "On Read the Docs" section, we have an issue to track that work in https://github.com/readthedocs/addons/issues/249. Please, subscribe there.
