### ISSUE TITLE
Bug: Read the docs failing on PDF build 

### ISSUE THREAD

**Issue by lwasser** [readthedocs/readthedocs.org#11539]
I've found a few issues related to pdf generation and RTD. [our build](https://github.com/stravalib/stravalib/blob/main/.readthedocs.yml) doesn't have the pdf option "turned on" as far as i understand but recently it has started to break with the error below. 

The build worked up until recently and I can build the docs locally and [in CI](https://github.com/stravalib/stravalib/actions/workflows/build-docs.yml) successfully. 

Can you help me understand why RTD is failing on our build? 

<img width="1161" alt="Screenshot 2024-08-13 at 6 43 01 AM" src="https://github.com/user-attachments/assets/8aeb4535-af9c-43df-822b-b5084331b0ad">

_Originally posted by @lwasser in https://github.com/readthedocs/readthedocs.org/issues/10549#issuecomment-2286176376_

**Comment by humitos** [comment]
Can you provide your project URL on Read the Docs and the URL for the failing build?

**Comment by lwasser** [comment]
hey @humitos 👋🏻 sure - 

https://stravalib.readthedocs.io/en/latest/

i'm not sure how to link to the readthedocs builds directly so please bare with me there! I see the build as a hook in an open pr.  if i can provide more information please let me know. 

https://readthedocs.org/projects/stravalib/builds/

<img width="859" alt="Screenshot 2024-08-13 at 9 28 14 AM" src="https://github.com/user-attachments/assets/bbd586df-8add-4b0a-8378-0e5985555f69">

**Comment by humitos** [comment]
You build process is generating more than 1 PDF file and Read the Docs does not support multiple PDF files as output. That's why you are getting that error message.

This is the build link showing the error that I'm referring to: https://readthedocs.org/projects/stravalib/builds/25297580/

You can either:

1. disable PDF builds for your project by removing this line in your config: https://github.com/stravalib/stravalib/blob/main/.readthedocs.yml#L8
2. configure Sphinx to ouput _only 1 PDF_ when building the PDF output: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_documents

The easiest solution is 1), in particular if you are not using PDF formats.

**Comment by lwasser** [comment]
oh gosh - thank you so much. i was looking for an explicit pdf config line not `formats: all`. This worked and we can close. I just have one question. Why did this just start to break in the past few days? Did something change on the RTD end of things?

**Comment by humitos** [comment]
> Why did this just start to break in the past few days? Did something change on the RTD end of things?

We haven't change anything about this in the past few days. I'm not sure what could be the reason of why it started failing now. Maybe your project is generating more than one PDF file now?
