### ISSUE TITLE
Broken flyout menu

### ISSUE THREAD

**Issue by francois-rozet** [readthedocs/readthedocs.org#11663]
## Details

The fly-out menu now appears on the right of the page, instead of at the bottom of the (left) sidebar, as it used to. This is an unexpected/undocumented change, so I assume it is a bug.

Examples:
- https://kornia.readthedocs.io/
- https://zuko.readthedocs.io/

**Comment by humitos** [comment]
Hi @francois-rozet! This is an expected behavior. We communicated this change as much as possible to all our users sending on-site notifications, post on social media, a post in our blog and opening issues. You may have missed those, but you can read more about it in https://about.readthedocs.com/blog/2024/07/addons-by-default/ -- and also check https://github.com/readthedocs/readthedocs.org/issues/11474 for more technical details.

Feel free to open another issue if you want to report specific bugs about the new addons.

**Comment by francois-rozet** [comment]
Thank you for the prompt answer! I do not follow RTD on social media so I missed that 😅 I would have noticed an email, but I don't know if you have access to the users' addresses. Anyway, thank you for your help.
