### ISSUE TITLE
load jquery and other javascript libraries with 'async'

### ISSUE THREAD

**Issue by mr-c** [readthedocs/readthedocs.org#1858]
Would speed up page renders: https://developers.google.com/speed/docs/insights/BlockingJS

https://developers.google.com/speed/pagespeed/insights/?hl=en&url=http%3A%2F%2Fmrc.commonwl.org%2F&tab=mobile

**Comment by ericholscher** [comment]
Sounds great, feel free to submit a PR that does this.

**Comment by dojutsu-user** [comment]
@ericholscher 
Is this still valid?

**Comment by stsewd** [comment]
I think @davidfischer did some of this?

**Comment by davidfischer** [comment]
For docs pages, I did look at something close to this: https://github.com/readthedocs/readthedocs-sphinx-ext/pull/75

However, due to the way Sphinx works, we cannot just make jQuery async as some code relies on it. If you want jQuery to be async, that would require changes in Sphinx itself and in the base theme.

**Comment by ericholscher** [comment]
Yea, I believe this should now be done. Sphinx supports this with the `add_js_file`: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file

And our files in the extension are using this and output as async. 👍

**Comment by mr-c** [comment]
Thank you @ericholscher et al. !
