### ISSUE TITLE
Doc javascript could be written to be less fragile on load order

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#2021]
Currently, there are a lot of assumptions about load order that make the theme work. Our scripts should probably eventually operate on events/defers or maybe just be written more defensively, to retry failed events. Some examples of this are loading the `READTHEDOCS_DATA` global, and our search overrides to the Sphinx search.

**Comment by davidfischer** [comment]
I think this is a fair issue to close out since it isn't super actionable as written.

Most of the JS that is inserted into generated docs are part of either the Sphinx basic theme or needed by Sphinx for search or other features. The ones RTD inserts are `readthedocs-doc-embed.js` (RTD search, ads, compatibility fixes), `readthedocs-analytics.js` (for analytics), `readthedocs-data.js` (data about the RTD build).

If I were to try to make it actionable, here's the things I'd want to do:

- Make `readthedocs-doc-embed.js` entirely self contained (except for the build data in `readthedocs-data.js`). It would need to vendor a library to make HTTP requests and possibly something to make inserting DOM items easier. We could probably do jquery-slim or something perhaps even slimmer. By vendoring these libraries, `readthedocs-doc-embed.js` wouldn't care about what order it is loaded in.
- If Sphinx ever supports the [async](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Attributes) attribute to JS tags, `readthedocs-analytics.js` should be async. This would be a small performance enhancement and basically the HTTP round trip would not impact DOM loading time.
- While there would be some challenges to make this backwards compatible, I would consider **not** making `readthedocs-data.js` a separate file and just removing it. The data in here can be generated from the Sphinx context and written inline in the HTML (eg. `<script id="READTHEDOCS_DATA" type="application/json">{...}</script>`). This would save an HTTP round trip and not pollute the global namespace.

**Comment by humitos** [comment]
I'm closing this issue since it's not gonna be a problem anymore with the new implementation of the client we are working on at https://github.com/readthedocs/readthedocs-client
