### ISSUE TITLE
unconditional new host redirect capability

### ISSUE THREAD

**Issue by zzzeek** [readthedocs/readthedocs.org#2267]
I'm in the process of migrating all of my documentation off of readthedocs.   While the projects I have which used their own subdomain don't have this issue, for projects served off of <projectname>.readthedocs.io, there's no capability to issue a global redirect to the new host.  While hacky approaches like uploading a sphinx build with a JS redirect might work, this is really not worth my time.  While I see that there are some limitations with redirects as per #1916, this is really just at the top level host entirely, and can be an alternative to the "404" page. 

Or even, if it were just possible for the 404 page itself to print the HTML, "project X has moved to Y", that would be enough.  As it stands, I'm going to have some frustrated users not finding my new docs for awhile (when they come to me, I'll point them to this issue :) ).

**Comment by eblume** [comment]
This was driving me nuts as we are in the middle of a major push to get our first alembic system going this weekend - I wish I had found the new location sooner! Thank you, zzzeek.

**Comment by ericholscher** [comment]
We'd be happy to support it -- best approach would be to submit a PR with tests & docs that solves this issue. Generally it's hard, because we serve media directly from nginx, so Python isn't hit unless we 404, so a patch would need to be an option set on a project, which deletes all the HTML files, and returns a redirect for all of them.

**Comment by ericholscher** [comment]
Thanks to @safwanrahman for the poke on this -- would be great to get this written and merged for folks!

**Comment by humitos** [comment]
> Generally it's hard, because we serve media directly from nginx, so Python isn't hit unless we 404, so a patch would need to be an option set on a project, which deletes all the HTML files, and returns a redirect for all of them.

I think I like this idea.

If we have an option under the admin that trigger in a broadcast way the deletion of _all_ the version of the current project, that will produce 404 in the nginx mechanism and Python will be reached.

At that point, we can check if that option is enabled and a redirect (previously defined by the user) will be returned.

This new options to mark this project as `moved` will enforce `skip=True`, otherwise a new build triggered will break all this logic.

I'd like to see this implemented since we were asked about this many times.

**Comment by humitos** [comment]
This could be implemented in El Proxito once we check for redirects before checking for existence of a file. See https://github.com/readthedocs/readthedocs.org/pull/6570/commits/a9dfbd08d1d492b7f5f478fd24428141e5969910 where we reverted this logic because it was incompatible with the current redirect behavior.

**Comment by stsewd** [comment]
A workaround is to add the new domain as custom domain and mark it as canonical. That will redirect everything to the new domain.

**Comment by humitos** [comment]
> Or even, if it were just possible for the 404 page itself to print the HTML, "project X has moved to Y", that would be enough

This can be done with https://sphinx-notfound-page.readthedocs.io/ extension.

Considering there are different ways to achieve this goal I don't think we will work on a solution "to move away fom RTD" soon. So, I will close this issue for now and we can revisit in the future if needed.
