### ISSUE TITLE
autodoc fails because of missing namespace package

### ISSUE THREAD

**Issue by azazel75** [readthedocs/readthedocs.org#3275]
## Details

* Project URL: https://readthedocs.org/projects/metapensierosignal
* Build URL (if applicable): https://readthedocs.org/projects/metapensierosignal/builds/6276037/
* Read the Docs username (if applicable):  azazel75

## Expected Result

That autodoc fills pages like http://metapensierosignal.readthedocs.io/en/latest/core.html with some content

## Actual Result
Due to this import errors (that I failed to reproduce locally) showed in the log of the fifth step of the build at the url above:
```
Running Sphinx v1.5.6
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 8 source files that are out of date
updating environment: 8 added, 0 changed, 0 removed
reading sources... [ 12%] api
reading sources... [ 25%] core
reading sources... [ 37%] external
reading sources... [ 50%] index
reading sources... [ 62%] intro
reading sources... [ 75%] user
reading sources... [ 87%] utils
reading sources... [100%] weak

/home/docs/checkouts/readthedocs.org/user_builds/metapensierosignal/checkouts/latest/doc/core.rst:19: WARNING: autodoc: failed to import class 'Signal' from module 'metapensiero.signal.core'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/metapensierosignal/envs/latest/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 560, in import_object
    __import__(self.modname)
ImportError: No module named 'metapensiero'
...
```
the api docs files like http://metapensierosignal.readthedocs.io/en/latest/core.html show that  no doc  is being outputted by autodoc

Anyone as any clue how to even reproduce this?

**Comment by agjohnson** [comment]
Are you installing your package? That is, do you have any of the `readthedocs.yml` or project admin settings set to install your package?

**Comment by azazel75** [comment]
@agjohnson yes, as the linked build shows in the third step. I've tried to depend on latest setuptools but doesn't change anything, but i see now that on step 2 setuptools==28.8 gets installed, which seems pretty old... I've to try and see If that is the culprit

**Comment by azazel75** [comment]
nope, even using setuptools==28.8.0 in a brand new venv and installing my package using python 3.5.4 works here on my machine, a debian linux

**Comment by stsewd** [comment]
I believe this is because `metapensiero` is not really a package, you need to add a `__init__.py` file on that folder to be considered as a module. And them edit your `setup.py` in this way:

- Remove this line https://github.com/metapensiero/metapensiero.signal/blob/ca75ba0c8859bead26b5e7ac566435df5adee156/setup.py#L47
- This https://github.com/metapensiero/metapensiero.signal/blob/ca75ba0c8859bead26b5e7ac566435df5adee156/setup.py#L44-L46 should be: 

```python
packages=[pkg for pkg in find_packages('src/')],
package_dir={'': 'src'},
```

With this I got your docs working on my local instance

![screenshot-2018-2-18 core an asyncio aware event framework documentation](https://user-images.githubusercontent.com/4975310/36359743-07bee4c4-14ec-11e8-9417-d079f064182d.png)

**Comment by azazel75** [comment]
Mmm.. I use native native namespace packages  ( packages without unuseful __init__.py files, See https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages) everywhere and they work very well, this is the only problem so far

**Comment by stsewd** [comment]
@azazel75 I checked the link, I didn't know about namespace packages :).

But reading, it gives you a real example https://github.com/pypa/sample-namespace-packages/tree/master/native

And I got your docs working (without the __init__.py file) with this:

```python
packages=['metapensiero.' + pkg for pkg in find_packages('src/metapensiero')],
package_dir={'': 'src/'},
# No need for this line, the package is namespaced automatically
# namespace_packages=['metapensiero'],
```

**Comment by stsewd** [comment]
@azazel75 can you please tell if my solution works for you?

**Comment by struegamer** [comment]
I encountered the same issue with a new project of mine.
Namespace package (`name/space/real_python_module_name/__init__.py`) can not be imported when using autodoc (like 
```
.. automodule:: name.space.real_python_pkg
    :members:

.. autoclass:: name.space.real_python_pkg.Classname
   :members:
   :private-members:
```

Error message always:

```
WARNING: autodoc: failed to import module 'real_python_pkg' from module 'name.space'; the following exception was raised:
No module named 'space'
```

Any fix for this?

Thanks

**Comment by stsewd** [comment]
Common bot!

**Comment by uweschmitt** [comment]
I have the same issue that implicit name packages are not supported somehow.

**Comment by stsewd** [comment]
We still need to dig a little more here. Would be great if someone could test if this happens outside read the docs in a clean environment, and following the same commands on the build page

**Comment by trulede** [comment]
I've encountered this problem today. It seems that if a namespace package as the same name as an existing package on the system, then the wrong package is opened.

For instance, a namespace package `foo.bar` which you want to document, and an existing package on the system `bar `... then that would trigger the error because autodoc opens `bar `rather than `foo.bar`.

**Comment by astrojuanlu** [comment]
hi @trulede , could you please open a new issue with more complete information for debugging? If it turns out to be a duplicate of this one, we can close and reopen.

**Comment by trulede** [comment]
Hi, well it's a bit tricky, certainly the same problem, but perhaps more generic.

It seems like this: if I have my namespace package called `foo.behave`, and also have a site package called `behave`, then the problem will occur. I guess that autodoc is trying to import the package/module `behave `(i.e. foo.behave) but actually picks up the site package `behave`, and from there things go downhill fast.

The solution (or at least workaround) is to insert the path to the namespace package so that python looks in that path first. So I kind of think this is going to be tricky to solve any other way.

A contributing factor is that for namespace packages we don't put an __init__.py in the namespace directory, so the python mechanism does not search any deeper down the directory tree. I think that is the correct thing to do. So, the above mentioned workaround is probably reasonable in this situation. I had been inserting the namespace path, but I think that is not sufficient in this case.

If I convince myself otherwise, then I will open a new issue. Thanks!
