### ISSUE TITLE
Missing i18n for footer and warning banner

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#3561]
## Details

The text displayed on the warning banner (when using an old version of the documentation) right now is hard coded on the js code.

https://github.com/rtfd/readthedocs.org/blob/b12e1885dc7f6da6b9719054e3654019b1e0fe65/readthedocs/core/static-src/core/js/doc-embed/version-compare.js#L18

Also the footer response from the API

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/restapi/templates/restapi/footer.html

Related comment https://github.com/rtfd/readthedocs.org/pull/3547#discussion_r163896883 

## Expected Result

Warning message and footer are translated according to the current language of the docs.

## Actual Result

The warning message and footer always display English text.

**Comment by stsewd** [comment]
We could for instance parse the current url `/en/latest/` and pass the lang to the API, or use the language from the current session.

**Comment by humitos** [comment]
We are already not using the banner by default on new projects. I think we should deprecate it, write docs suggesting https://github.com/humitos/sphinx-version-warning/ which is more configurable and finally remove our own banner.

In case we need something extra, we can add those features to that extension which will be easier and we could support different setups instead of hardcode only one into our codebase.

**Comment by stsewd** [comment]
Yeah, we can ignore translating the warning banner for now, footer api still needs translation

**Comment by saadmk11** [comment]
@stsewd We can use something like this to use django translation on the javascript code.
https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#internationalization-in-javascript-code

but what needs to be translated on the footer API response?
do you means texts on the `footer.html` template like: `Languages` `Versions`
