### ISSUE TITLE
Confusing build failed message (time out and memory consumption)

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4468]
Recently I have seen some reports of build failure like https://github.com/rtfd/readthedocs.org/issues/4443, where the failed build display two different messages as the failure reason.

Here you can see an example https://readthedocs.org/projects/oapackage/builds/7559891/. The error message is `Build exited due to time out`, but the last command that was executed failed with ` Command killed due to excessive memory consumption`.

**Comment by agjohnson** [comment]
This is because the best guess we have when docker kills something is looking for the `137` exit code, which usually indicates that memory was an issue. Unfortunately, we don't have a better way to determine this, so we're likely to get false positives. What happened here is project timed out, killing the process inside docker, reporting the exit code as `137`.

Not sure if there is a lot we can do here, or if there is, if there is much benefit.

**Comment by stsewd** [comment]
> Not sure if there is a lot we can do here, or if there is, if there is much benefit.

mmm, I haven't see the code, but we could try to get the error from the latest command (I think we already inspect the output), so both error messages match. Right now is confusing for the users, and gives a wrong hint about the problem.
