### ISSUE TITLE
Cleanup exception that are not logged as error

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4590]
After #4495 got merged @agjohnson suggested to have an attribute in the Exception class and check for that attribute before log the exception, instead of defining a list for the warning exceptions as I did at:

https://github.com/rtfd/readthedocs.org/pull/4495/files#diff-ca52b098301dd315a834b3556ab9a7d5R424

Also, there are more exceptions that have to treat in the same way: `ProjectConfigurationError` for example.

https://sentry.io/read-the-docs/readthedocs-org/issues/668248681/

**Comment by agjohnson** [comment]
This is cleanup milestone, deprioritizing for now.

**Comment by humitos** [comment]
I think this is easier to do by defining `Task.throws` and using the proper Sentry setting `SENTRY_CELERY_IGNORE_EXPECTED` for this.

**Comment by dojutsu-user** [comment]
@humitos 
I think this can be closed now.

**Comment by stsewd** [comment]
I think we still need https://github.com/rtfd/readthedocs.org/pull/5073 to close this

**Comment by stsewd** [comment]
This is still valid. We are logging manually those exceptions to sentry

https://github.com/readthedocs/readthedocs.org/blob/72972b53e5bb2cc13235bc4223a7d3990f24d50f/readthedocs/doc_builder/environments.py#L606-L622

From projects/tasks.py we are re-raising some exceptions to don't fall into the genereal `Exception` block and don't log those (#6112).

And we haven't removed the old code :)

https://github.com/readthedocs/readthedocs.org/blob/72972b53e5bb2cc13235bc4223a7d3990f24d50f/readthedocs/doc_builder/environments.py#L536-L542

There is no way to fix this using `throws` on the task. And we can't re-raise the exception because that will break many places.

And using the `BuildEnviroment` should know nothing about the exception on `WARNING_EXCEPTIONS`. So, we could pass on the BuildEnvironment constructor an arg like `ignore_exceptions=()` with all classes that we want to be ignored. Or Just remove the code that manually logs those errors and each part that uses a buildenviroment should be in charge of catching those, buildenviroment will only handle BuildEnvironmentWanings.

**Comment by ericholscher** [comment]
I feel like this is now solved. Re-open it if not 👍
