### ISSUE TITLE
django-cors-middleware package is obsolete

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4694]
We are using this package https://github.com/zestedesavoir/django-cors-middleware which says that it's a fork of https://github.com/ottoyiu/django-cors-headers because it was inactive.

Although, the `django-cors-headers` has an update 8 days ago and `django-cors-middleware`'s latest update is a year ago.

We may want to switch to the original package at some point.

**Comment by dojutsu-user** [comment]
@humitos I would like to work on this issue. Can you please guide me on how to get started with this?

**Comment by agjohnson** [comment]
This issue is in our Cleanup roadmap, and so is currently off the roadmap for core team. We can't dedicate too many resources to helping out here, and this issue requires a lot of knowledge of how Read the Docs works. Feel free to take this on still, but perhaps a good place to start is in our docs:
https://docs.readthedocs.io/en/latest/install.html

More info on our roadmap:
https://docs.readthedocs.io/en/latest/roadmap.html

**Comment by dojutsu-user** [comment]
@agjohnson Thank you for telling me. I am not that much familiar with the working of the RTD yet. However, if this issue remains open, I would be the one to work on this in future.

**Comment by humitos** [comment]
I'm closing this issue. The packages has an update 21 days ago.
