### ISSUE TITLE
Allow to flag a project as spam

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#5227]
Looks like we used to support this feature a long time ago

https://github.com/rtfd/readthedocs.org/tree/master/readthedocs/templates/flagging

But isn't used, we should reconsider exposing this feature to help us fight spam

Related https://github.com/rtfd/readthedocs.org/issues/5218

**Comment by agjohnson** [comment]
I'm probably -1 on this, as our problem now isn't that we don't know *what* is spam, it's that we don't have the resources to review projects consistently. Adding more data here is likely not particularly useful, and I don't think we'd ever add an automated way to ban projects as that would be a great target for abuse.

I'd rather invest more time into catching these projects before users do, and developing a workflow to make removal less of an administration burden, so it happens more frequently.

**Comment by humitos** [comment]
> I don't think we'd ever add an automated way to ban projects as that would be a great target for abuse.

I have some ideas about this, for example:

1. write a management command to use internally
1. it "auto detects" SPAM projects that are already in the database
1. show N projects to the user (where N is a reasonable number to review. Let's say ~25)
1. ask the users to specify which one are spam (like `1-5, 15, 20-25`)
1. save spam data into a different model (`SpamProject`) to keep training our model
1. delete those projects and mark the users as banned

After some months of collecting this data and training our model, we can rely on #5038 with a better accuracy.

**Comment by agjohnson** [comment]
I'm not a fan of hiding operations tasks in management commands, code tends to rot there.

I'd rather we focus on the admin dashboard, this seems like a great chance to add more there, and would accomplish most of what you're describing out of the box with the admin.

Perhaps we could add better filters to make :

* Probably spam -- have some query terms that are usually spam, add this as an admin filter
* Maybe spam -- maybe a less aggressive version of this?
* Not spam -- i don't know if there is a good query for this though

Also in the admin, some actions:

* Classify as spam -- if this isn't accomplished through my last text-classifier, but I think it already is. We already have a ban project user, which is the action i normally take on classifying projects
* Test classification action -- test the project against our spam classification

I'm still hesitant to auto-cleanup here. Autocleanup would look at banned users and remove their projects. We could make logic that pulls banned users where they are the only user of the project and auto-delete those projects.

The most expensive part of the process is the deletion process in the admin, because you have to go through each screen to delete a batch of spam projects. The django admin can't display such a larger query and the hierarchy of changes. We could maybe make a `delete projects asynchronously` action, which doesn't show these changes?

**Comment by davidfischer** [comment]
> I'm still hesitant to auto-cleanup here. Autocleanup would look at banned users and remove their projects. We could make logic that pulls banned users where they are the only user of the project and auto-delete those projects.

This is the path more or less that I'm taking in the private issue: https://github.com/readthedocs/readthedocs-ext/pull/249

Flagging/banning users would still be a manual process but at least the cleanup would happen automatically.

**Comment by astrojuanlu** [comment]
I've handled two emails these past two days from people sending us a list of spammy projects. What is the current status of text classifier @agjohnson mentions above?

Even though we don't have a way for users to flag projects as spam, shouldn't we at least have such option ourselves, and then manually hide the projects? This allows us to

1. Slowly collect spammy projects, that can perhaps inform an automatic algorithm in the future,
2. Hide the project without removing it, in case the flagging is incorrect

**Comment by agjohnson** [comment]
Spam projects are rather obvious, so hiding them is probably just extra steps. We do need to perform the spam cleanup steps more frequently however. We were better about this in the past.

We haven't worked on features to address spam much at all. Currently it's easier to just go through the admin and ban users, then delete their projects. We could mock the user reporting interaction if we want though, and just drop a message into a Front form with the project details. I'm not sure there is strong value in modeling project spam classification etc at the moment.

**Comment by humitos** [comment]
We already implemented some techniques to deal with spam and we are happy so far. I'm closing this issue. We can revisit if we find ourselves dealing with a lot of spam again.
