### ISSUE TITLE
Add note about the constrains of using conda

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#5388]
We should mention the restrictions of using conda, a better approach would be to raise an exception in the validation process, but that would break some projects, so that's not possible now.

Constraints:

- The virtual environment creation in managed by conda
- So, `syste_packages` does't have any effect
- The python version doesn't have any effect, that's managed by conda
- We don't install requirements from files here (but we could do it https://github.com/rtfd/readthedocs.org/issues/2776)

Docs that should be changed https://docs.readthedocs.io/en/stable/config-file/v2.html#conda

Maybe the docs from v1 too? and the page about conda support?

Ref https://github.com/rtfd/readthedocs.org/issues/5387#issuecomment-468976955

**Comment by Mike-Dai** [comment]
Can I work on this issue?

**Comment by humitos** [comment]
@Mike-Dai hi! I think the actions for this issue are not well defined yet. Although, if you want, you can start with a proposal of how to do it and what to change and where (considering the context that Santos wrote in the description)

**Comment by Mike-Dai** [comment]
@stsewd  @humitos 
Here is my proposal:
1.In `docs/config-file/v2.rst`, add a warning below `python.system_packages`, which says "If you install your project with conda, you should not set the value to `True`. Because the virtual environment creation in managed by conda. So, `syste_packages` does't have any effect."
2.In the same file, add a note below `python.verison` part, which says: "If you use conda, the python version doesn't have any effect, that's managed by conda."
3.In the same file, Add a note below `Requirements file` part, which says: "If you use a conda environment, we don't install requirements from files here. You have to put the pip requirements inside the `environment.yml` used by conda." 
4.If we need to modify the `Conda support` page, I will add a warning in `docs/conda.rst` that includes all constraints.
5.If we need to modify the V1 docs, I will made respective change similar to V2 docs.
6.According to the advice given in issues #5387, maybe we can add a link in `conda` part to tell users [use pip when possible](https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html#use-pip-when-possible). Also, we can add a warning to remind users that RTD can't handle building too big conda environments.

**Comment by Mike-Dai** [comment]
Should I open a PR or wait for more discussion? Please let me know if any changes required.

**Comment by humitos** [comment]
@stsewd what do you think about @Mike-Dai proposal?

**Comment by stsewd** [comment]
@humitos, @Mike-Dai looks great, we should add the same notes under the conda setting too.

**Comment by namanbansal013** [comment]
@stsewd I'd like to work on this issue. Should I add the constraints to docs of v1 too? Also, I'm not able to locate conda support page. Can you please guide me through it.

**Comment by stsewd** [comment]
@namanbansal013 starting with updating the v2 docs should be a good first step, we can see if it
s needed to update other places after that.

**Comment by Parth1811** [comment]
I'm starting work on this issue as I see no new updates recently. @namanbansal013 if you have made any progress, please do share with me.
