### ISSUE TITLE
Add analytics code per-version using a config file

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#5478]
This is currently a per-project option currently.

Ref https://github.com/rtfd/readthedocs.org/pull/5459#discussion_r266131947

My doubt about this: Don't people use just one analytics code per site? And also, isn't a way of identify each page from analytics?

Also, one good thing is people changing their analytics code over time.

**Comment by humitos** [comment]
@davidfischer can you expand here? I'm not sure if in your linked comment you refer specifically to the `analytics_code` setting or another portion of that code.

I'm not sure to understand why having an `analytics_code` per version would be useful.

**Comment by davidfischer** [comment]
I missed this when it was opened but I'm glad you followed up.

For the vast majority of cases, I suspect that all versions of a project would want the same analytics code. With that said, I could envision a case where certain versions don't want to send data to GA. The bigger advantage I see is that this adds the analytics code to version control rather than having a project level setting.

**Comment by davidfischer** [comment]
Looking back, nobody has given a use case for making analytics per version. If the setting is project-wide and not version specific, I'm in favor of closing this and making it a project level setting.
