### ISSUE TITLE
Move in-doc download links away from project dashboard page

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#5855]
In a focus to keep the reader user experience solely in documentation, we are planning on moving elements from the project dashboard and into in-doc UI. One of the places that we are pointing reader users into the project dashboard is with format download links.

- Change the location of the footer download links, don't point to the project dashboard
- We have these assets in our external storage, this should be the ultimate location for the download links

**Comment by agjohnson** [comment]
A solution here should be able to hide the use of RTD completely -- no link to `buildmedia.readthedocs.org` or to the project dashboard downloads page. A couple of options here might be:

* Add files to the build output directory and reference via relative link
* Support custom domains in the resolution of the download links

**Comment by humitos** [comment]
> Support custom domains in the resolution of the download links

My vote would be this option, if it's not extremely complicated. This will allow us to have a better experience when "whitelisting" a set of documentation.

**Comment by tapaswenipathak** [comment]
Hello @agjohnson, @humitos: Interested in this ticket, doing.

**Comment by stsewd** [comment]
Hi @tapaswenipathak, this issue isn't a good first issue to start if you are not familiar with the project (also I think there is still a design decision to make).

Please feel free to ask any questions

**Comment by tapaswenipathak** [comment]
Hi @stsewd: I just posted few questions in Gitter.

**Comment by tapaswenipathak** [comment]
Thanks for letting me know, I will add few things in the PR.

**Comment by davidfischer** [comment]
I think there's a few bits here:

* Firstly, removing the "Downloads" link in the flyout menu that links to the downloads page of the RTD dashboard. For that, https://github.com/readthedocs/readthedocs.org/pull/6100 looks pretty good to me.
* Currently, when requesting a download the request is redirected to cloud storage (eg. `https://readthedocs.org/projects/docs/downloads/pdf/latest/` -> `https://buildmedia.readthedocs.org/media/pdf/docs/latest/docs.pdf`). There was talk (in a private issue https://github.com/readthedocs/readthedocs-ops/pull/557#issuecomment-522048224) of using internal redirection via [Sendfile](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/). This would allow us to have links that we could redirect and change later without having to worry whether users have bookmarked a cloud storage URL. I'm on board with this. :+1: 
* Lastly, should we use custom domains in resolution of download links? For example, should we have something like `https://docs.godotengine.org/downloads/pdf/3.0/` instead of `https://readthedocs.org/projects/godot/downloads/pdf/3.0/`. This gets a little tricky since we are adding a path to a custom domain that doesn't exist. There could be collisions here especially with single version projects.

<img width="626" alt="Screen Shot 2019-09-13 at 11 40 45 AM" src="https://user-images.githubusercontent.com/185043/64886762-c50dfc80-d61b-11e9-9370-750fbb6cd4a9.png">

**Comment by tapaswenipathak** [comment]
Hey @davidfischer: I can take a look. Thanks for writing notes.

**Comment by tapaswenipathak** [comment]
Hey @davidfischer: Thanks for the notes.

**Comment by stsewd** [comment]
> There could be collisions here especially with single version projects.

Maybe something like we do with .com? Adding a prefix `_/downloads`

**Comment by davidfischer** [comment]
> Adding a prefix /_/downloads

That sounds fine to me.

**Comment by humitos** [comment]
> Firstly, removing the "Downloads" link in the flyout menu that links to the downloads page of the RTD dashboard. For that, #6100 looks pretty good to me.

I think that PR removes the `ePub`, `PDF` and `HTML` links ("Download" section), not the `Downloads` link. I think we don't want that.
