### ISSUE TITLE
yaml config can't specify exact build image

### ISSUE THREAD

**Issue by davidism** [readthedocs/readthedocs.org#6039]
In order to keep builds reproducible, I want to specify versions to use. I can do this for requirements and Python, but not for the build image, which only has "stable" and "latest" values. This is looking far into the future, but if "latest" changes to an image that doesn't have the Python I've configured, and I need to rebuild the docs for some reason, the build will now fail. Names like "ubuntu-18.04" should be available.

This might already be possible, since the Docker images have versioned tags, but if so that's not documented.

**Comment by humitos** [comment]
Hi David! We had this discussion internally already and, as our Docker images are pretty big (~8gb each), supporting old versions "kind of forever" means a lot of space for this in our builders.

We only document `stable` and `latest` only because they should be enough for (most) users to build their docs. We don't do (or should not do) incompatible changes in our Docker images --although, since some versions of libraries are updated on each release, the change may be incompatible for someone's else docs.

Although it's not documented (on purpose), you can pin a specific Docker build image in the YAML, but I'm not sure we can guarantee they will be there forever.

**Comment by davidism** [comment]
Thanks, I'll think about if I need to pin to "5.0" vs "latest".
