### ISSUE TITLE
Link to commit hash and PR on docs built from a PR

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6303]
When we build docs from a PR we put this banner

![Screenshot_2019-10-17 Read the Docs Documentation Simplified — Read the Docs 3 8 0 documentation](https://user-images.githubusercontent.com/4975310/67023717-e0f83880-f0c8-11e9-9c14-b8194b2ff3a6.png)

But the users don't know from what commit are those docs. It would be also helpful to link to the PR + show the commit.

**Comment by eric-wieser** [comment]
As I mentioned in the email that spawned this issue - I would go further with this:

* Have docs be linked at `https://external-builds.readthedocs.io/html/<project>/<pr>/<commit-sha>/index.html`, so that permalinks can be created to docs
* Create an alias at `https://external-builds.readthedocs.io/html/<project>/<pr>/latest/index.html`, which redirects to the above.
* Have some kind of reasonable "doc build discarded, see the most recent build here" error page for users who click the `/<commit-sha>/` link after the build artifacts for that commit have been deleted, which links statically to `/latest/`

**Comment by humitos** [comment]
I think this was already implemented. I'm seeing this now:

![Screenshot_2022-01-27_21-47-32](https://user-images.githubusercontent.com/244656/151441116-968d06cb-4c56-436e-b0ae-bcb104090708.png)

Do we want to show the commit number as well?

**Comment by stsewd** [comment]
The link to the build already has the commit, but I see being useful to have the commit there,  so not sure.

**Comment by humitos** [comment]
OK. From my point of view, I don't think the specific commit is important enough to be linked from the documentation page. So, I will close this issue. We can come back if we feel it's important and we want to add it.
