### ISSUE TITLE
Build of `latest` version fails because it tries to do `hg update --clean latest`

### ISSUE THREAD

**Issue by vsajip** [readthedocs/readthedocs.org#6337]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/distlib/
* Build URL (if applicable): https://readthedocs.org/projects/distlib/builds/9879428/
* Read the Docs username (if applicable): vsajip

## Expected Result

Build works correctly.

## Actual Result

Build fails because it tries to do `hg update --clean latest` which predictably fails with `abort: unknown revision 'latest'!`. The full sequence of build commands issued is:

```
hg pull
hg update --clean
hg tags
hg branches --quiet
hg update --clean latest
```

**Comment by humitos** [comment]
The last command should be `hg update --clean tip`, right?

Did you create a `latest` tag or branch in that repository at some point?

**Comment by stsewd** [comment]
Checked on the db, the branch isn't marked as machine created, I think this was from before whe changed how latest get's updated (users can create their own latest).

Anyway, this is because you have your default branch as `latest` in your project's settings https://readthedocs.org/projects/distlib/edit, it should be empty to get the default or the branch that you expect to be built.

**Comment by vsajip** [comment]
> it should be empty to get the default or the branch that you expect to be built.

OK, thanks. It builds as expected now.
