### ISSUE TITLE
Allow to re-trigger a build from the build page

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6524]
This is mainly for builds from a pull request (maybe would be good to add this to normal builds too?), sometimes the build fails for reasons that aren't related to the PR like https://readthedocs.org/projects/docs/builds/10259706/.

The status of the PR would be marked with the red X because of that. Travis and other services allow you to trigger a new build to refresh the status.

Currently, the only way to trigger a new build is by making another commit. 
We could allow to re-trigger a build only on unsuccessful builds or maybe in all builds.

**Comment by stsewd** [comment]
The link gives 404 now because we delete all builds when the PR is merged/closed :D

**Comment by saadmk11** [comment]
I think we can show a `Restart Build` button on the build detail page for the `External` versions and it should be only available to the maintainers of the project.

**Comment by pllim** [comment]
Hello. I was looking for this feature as well. 

FWIW, I think allowing trigger for both failing and successful builds is useful. This is because sometimes as a maintainer, I want to know if new upstream release on PyPI would break an already successful PR build.

Also would be nice to have a "wipe cache" option. Currently some builds are failing due to invalid cache for pip 20.0. A wipe is necessary before rebuild.

**Comment by ericholscher** [comment]
This is really useful for the PR builder. I think we need to figure out a good way to ship this 👍

**Comment by chaen** [comment]
+1 on the feature. We are hit by this problem when the build crashes (e.g. `Command killed due to excessive memory consumption`) and it is a pity to have to re-run 50 other tests that passed just because of that.
