### ISSUE TITLE
mocked import of pyodbc needs 3 builds to succeed

### ISSUE THREAD

**Issue by mikkelee** [readthedocs/readthedocs.org#6528]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/correctocr/
* Build URL: https://readthedocs.org/projects/correctocr/builds/10270732/ (failed)
* Build URL: https://readthedocs.org/projects/correctocr/builds/10270737/ (failed)
* Build URL: https://readthedocs.org/projects/correctocr/builds/10270739/ (completed)
* Read the Docs username: mikkel.eriksen@gmail.com

## Expected Result

Build succeeding on first run.

## Actual Result

The build fails on `import pyodbc` though it is mocked in `conf.py`. I did not push to the repo but double-checked my `conf.py` and `requirements.txt` and ordered new builds until it succeeded (3rd try).

Note that the first time it fails on building `readthedocssinglehtmllocalmedia` and the second time on `latex`.

**Comment by stsewd** [comment]
@mikkelee the builds that failed were using a cached environment, you can see this by looking into the git clone step, it uses `git fetch` instead of `git clone`. The build that succeeded was in a clean environment. This isn't usually a problem, but it can be sometimes when the requirements change https://docs.readthedocs.io/en/stable/guides/wipe-environment.html
