### ISSUE TITLE
missing anchor/perm links in RTD

### ISSUE THREAD

**Issue by Borda** [readthedocs/readthedocs.org#6661]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pytorch-lightning
* Build URL (if applicable): https://readthedocs.org/projects/pytorch-lightning/builds/10446397/
* Sphinx config: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/conf.py
* Read the Docs username (if applicable): Borda

## Expected Result

We have updated the config accordingly to have the anchor link and tested locally as you can see at the attached print-screen where everything works fine... https://github.com/PyTorchLightning/pytorch-lightning/pull/848
![image](https://user-images.githubusercontent.com/6035284/74602347-d023f780-50a7-11ea-81b8-4d038293b71a.png)

## Actual Result

After building on RTD, the anchor links are still missing even the build pass successfully

**Comment by humitos** [comment]
Hi! I do see an anchor link in this page https://pytorch-lightning.readthedocs.io/en/latest/loggers.html#module-pytorch_lightning.loggers

is that what you are reporting? I'm not sure to understand it 100%.

**Comment by Borda** [comment]
I am talking about this twisted circles next to the header, and I do not see then even after passing over with cursor... I have tried Chrome and Mozilla browser
![docs-links-smalll](https://user-images.githubusercontent.com/6035284/74656014-a93ff100-518d-11ea-987a-93e036df49a7.png)

**Comment by humitos** [comment]
Yes. That's where I get the link that I pasted. It works for me on Firefox but it doesn't on Google Chrome. This is probably a bug of the theme.

**Comment by Borda** [comment]
for me using the same browser I see it in local docs but not in the RTD... @williamFalcon

**Comment by stsewd** [comment]
I can see it on firefox too, try running firefox without any extension.

**Comment by neggert** [comment]
I see missing links in Firefox on RTD, and also a bunch of errors in the JS console that look related. I suspect you're correct about a problem with the theme.

**Comment by luiscape** [comment]
I agree with @neggert I think the issues here are with the theme (specifically, the JS library AnchorJS isn't being loaded correctly affecting the generation of anchor links).

**Comment by luiscape** [comment]
Ok so the issue here is an incompatibility of the theme used with the extension `nbsphinx`. The extension uses RequireJS to convert Jupyter Notebook widgets into documentation. When RequireJS is injected in the resulting `index.html` file it messes up the loading of other required libraries by the theme, AnchorJS among them -- hence no anchors. 

A quick solution for this problem (as per [documentation](https://nbsphinx.readthedocs.io/en/0.5.1/usage.html)) is to disable the loading of RequireJS in the `nbsphinx` theme with:

```python
nbsphinx_requirejs_path = ''
```

See solution working:

![Kapture 2020-02-18 at 23 31 32](https://user-images.githubusercontent.com/953118/74802166-0085b480-52a7-11ea-9471-e795a903f492.gif)

I suggest closing this issue. I'll make a PR against the theme to fix this there.

**Comment by stsewd** [comment]
@luiscape thanks for the explanation and workaround!
