### ISSUE TITLE
Automatically imported project not showing in projects list

### ISSUE THREAD

**Issue by usask-rc** [readthedocs/readthedocs.org#6677]
## Details

* Read the Docs project URL: https://radiam.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): usask-rc
* Github repo URL: https://github.com/usask-rc/radiam

After connecting GitHub to RTD, when I went to the page https://readthedocs.org/dashboard/import/ the project status was "already imported". However, it does not show up in the list of projects.

## Expected Result

The automatically imported project should appear at:
https://readthedocs.org/dashboard/

## Actual Result

It does not appear.  Additionally, it does not have an "admin" button, in contrast to manually imported projects which do have one.

**Comment by stsewd** [comment]
@usask-rc can you please attach some screenshots of what you are seeing? I think I have an idea, but just want to be sure

**Comment by usask-rc** [comment]
![Screen Shot 2020-02-19 at 10 27 47 AM](https://user-images.githubusercontent.com/19416365/74852726-9d297000-5302-11ea-990a-0c44af485e70.png)

**Comment by usask-rc** [comment]
![Screen Shot 2020-02-19 at 10 27 57 AM](https://user-images.githubusercontent.com/19416365/74852753-a61a4180-5302-11ea-90fe-4e2658a04d6e.png)

**Comment by usask-rc** [comment]
![Screen Shot 2020-02-19 at 10 33 45 AM](https://user-images.githubusercontent.com/19416365/74853290-5720dc00-5303-11ea-87d2-8dfb206b4cdb.png)

**Comment by usask-rc** [comment]
Last one (3 of 3) uploaded

**Comment by stsewd** [comment]
@usask-rc looks like the project on rtd is owned by https://readthedocs.org/profiles/axfelix/.

I think the user has permissions over your repo, so the user imported it first on rtd (this is allowed because the user has permissions over that repo).

This is also related to https://github.com/readthedocs/readthedocs.org/issues/2759

Solutions:

- Ask the user to give you permissions over the rtd project
- Manually import your project under another name

**Comment by usask-rc** [comment]
OK thanks for the update, I will contact Alex.  I don't think this behaviour is good, however this at least clears up my confusion.
