### ISSUE TITLE
torch, tensorflow and other big packages fail when installing

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#6742]
We are currently failing all builds installing any of the following packages. They fail at the `pip install` step because OOM.

List of known packages that fail so far:
- pytorch
- torch
- tensorflow
- (another)

Unfortunately, we do no have a workaround currently. Increasing the memory limits has not helped a lot when tried. For now, we suggest you to follow our guide to reduce the resource consumption https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html

I'm creating this issue to have one and only one place to track this down and also because users can subscribe to this issue for news.

> We have a branch on `test-builds` to try `pytorch`. A failing build, https://readthedocs.org/projects/test-builds/builds/10553088/

Reference: #6727 #6664 #6537

**Comment by ericholscher** [comment]
I believe the current plan is to roll out a large memory set of builders behind the `build:large` queue in our backend. Then we will give builds on those builders ~4GB of memory.

**Comment by faustomorales** [comment]
One way to avoid this issue entirely is to use stubs for the big packages instead of installing them. This is a suitable option assuming the only reason you need the package is to prevent imports from failing. I implemented such a solution for TensorFlow using https://github.com/faustomorales/keras-ocr/commit/e25f11be3e0fc8dc4422492f391d60c2a32dc1a2. Naturally, if you're actually *using* TensorFlow as part of your build, this will not be suitable for you.

The benefits of this approach are that it makes my builds *much* faster and also, hopefully, saves readthedocs.org some money by avoiding the download of a >400MB package (and use of a high memory instance) on each build that isn't actually needed to generate documentation (for me).

Hope this helps someone out there! :)

**Comment by humitos** [comment]
I just tested this in the new infra at https://readthedocs.org/projects/test-builds/builds/10881199/ and it was executed by `build:default` queue. It succeed without problems.

Besides, I haven't heard more users reporting this kind of issues anymore. We can probably close this issue now.

In case we hit this again, we could add a new rule in our router that checks if any of these packages are in the `requirements.txt` file to decide routing it to `build:large` --I don't really like that, though.

**Comment by Trinkle23897** [comment]
@humitos It still has this problem. See https://readthedocs.org/projects/tianshou/builds/10931997/
I add torch in my setup.py and it fails to download this package in some cases. I'll test your "./sutbs" method later.

**Comment by Trinkle23897** [comment]
Oh, after I re-add the torch package in docs/requirements.txt, it seems to be much faster.

**Comment by humitos** [comment]
@Trinkle23897 happy that it worked. However, the build linked had a problem about time out not OOM (which was this issue about).

Keep me posted if you still have this or any other issue building with these packages.

**Comment by astrojuanlu** [comment]
When I first saw this issue I thought "maybe some projects are installing these big dependencies from source, then the RTD builder tries to compile them, then it gets killed by the OOM". However, it's evident from the builds that the binary wheels are getting pulled in all cases.

It turns out that, when installing a big wheel, there is a large RAM spike by pip. I managed to take a couple of screenshots:

![Screenshot from 2021-02-27 21-39-38](https://user-images.githubusercontent.com/316517/109399687-9cc7aa00-7944-11eb-9fb3-c2b1db032c87.png)

![Screenshot from 2021-02-27 21-41-15](https://user-images.githubusercontent.com/316517/109399693-a224f480-7944-11eb-86ce-d2320227be81.png)

That's 3 GB of RAM to install a ~800 MB wheel. I did a quick search on the pip issue tracker and I don't see any mentions to this issue. Can someone confirm?

**Comment by ericholscher** [comment]
@astrojuanlu super interesting. If we can figure out a good way to keep memory usage reasonable, I think this will help a lot of projects.

**Comment by astrojuanlu** [comment]
https://discuss.python.org/t/large-ram-spike-when-caching-large-wheels/7465?u=astrojuanlu Some preliminary investigation suggests that this happens during the caching phase. I see that RTD calls pip with `--cache-dir /home/docs/checkouts/readthedocs.org/user_builds/test-builds/.cache/pip` (probably to try to avoid downloading the same dependencies every time). Will keep you posted.

**Comment by stsewd** [comment]
We use ephemeral builds now, so we can just remove that argument (or add it only when using the https://github.com/readthedocs/readthedocs.org/blob/0f7c708b96e2b860732ab2b7593ccbf8c5ceb93b/readthedocs/projects/models.py#L1667-L1667 feature flag)

**Comment by stsewd** [comment]
but looks like we already do that https://github.com/readthedocs/readthedocs.org/blob/0f7c708b96e2b860732ab2b7593ccbf8c5ceb93b/readthedocs/doc_builder/python_environments.py#L126-L150

**Comment by astrojuanlu** [comment]
It turns out that the excessive RAM consumption during pip caching is known since 2015 https://github.com/pypa/pip/issues/2984

**Comment by humitos** [comment]
We are updating pip on each build, so I guess we will stop having this problem once `pip` makes a new release with this fix 💯
