### ISSUE TITLE
Build fails after checking out submodules (build id #10564602)

### ISSUE THREAD

**Issue by Bjwebb** [readthedocs/readthedocs.org#6754]
## Details:

* Project URL: https://readthedocs.org/projects/beneficial-ownership-data-standard
* Build URL(if applicable): https://readthedocs.org/projects/beneficial-ownership-data-standard/builds/10564602/
* Read the Docs username(if applicable): bjwebb

## Expected Result

Build succeeds.

The same commit worked back in February: https://readthedocs.org/projects/beneficial-ownership-data-standard/builds/10502015/

## Actual Result

Build fails after checking out submodules.

There's no detailed error message, just a generic "There was a problem" message at the top.

**Comment by humitos** [comment]
Hi! I found the issue.

You are pinning the build image to `2.0` which is an outdated image and it's not available in the servers anymore. We do not document that pinning to numbered images is possible because of this reason. If you go to the docs, you will notice that only `stable` and `latest` are allowed.

Please, change the value to `stable` or `latest` and your builds will start passing again.

Feel free to reopen the issue if this does not work.
