### ISSUE TITLE
Command killed due to excessive memory consumption during conda env create

### ISSUE THREAD

**Issue by duncanmmacleod** [readthedocs/readthedocs.org#6757]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/requests-ecp/
* Build URL (if applicable): https://readthedocs.org/projects/requests-ecp/builds/10577754/
* Read the Docs username (if applicable): duncanmmacleod

## Expected Result

Build passes.

## Actual Result

Build fails immediately while attempting to initialise a conda environment creation.

**Comment by humitos** [comment]
Hi @duncanmmacleod! I recommend you to take a look at https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html and in particular the section that talks about using `pip` for creating the environment. Let me know if that helps.

**Comment by duncanmmacleod** [comment]
hi @humitos, the main problem with just using `pip` is that this package needs `pykerberos`, which is compiled, and can't be built on-the-fly it seems on the RTD images [[build log](https://readthedocs.org/projects/requests-ecp/builds/10578707/)]. However I have been able to proceed with conda build if I reduce the package set so that I don't need to use `conda-forge`.

Since I've had the same problem with two different packages (see #6743), is it worth adding a note to the documentation that you basically can't use the `conda-forge` channel with RTD conda builds unless you are given extra resources?

**Comment by humitos** [comment]
> is it worth adding a note to the documentation that you basically can't use the `conda-forge` channel with RTD conda builds unless you are given extra resources?

A note saying to try this out as a first step could works, but we definitely want to support being able to use `conda-forge` channel. If you have some time, you can open a PR with a proposal for this. I'd appreciate that.

BTW, we already released a set of new builders and we are currently testing them, but those should fix this problems around not enough memory when running conda.

I understand that your issue is solved by now, so I'm going to close this issue. Feel free to reopen or open a new one if you consider. Thanks!
