### ISSUE TITLE
Remove fake broadcast operations against builder queues

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#6775]
Currently, we're using a fake broadcast task to trigger removal of paths on all build servers. With the move to scaling groups, the webs will no longer be tracking the individual build servers, and so our broadcast method of looping over `APP_BUILD_SERVERS` will not work anymore.

It's not clear if we even need these operations anymore however. This would probably be the place to start, and if not, we can start stripping out code when we're close to single process builders.

Otherwise, we might need to look into proper broadcast on the build queues.

**Comment by humitos** [comment]
We do not need this `broadcast` function anymore. IIRC, I removed them all in #6535 but I left it there because it was only needed for the builders to wipe versions. However, that won't be needed anymore if we are going to use "always clean" or if we used the shared cached environment via storage (#6763).
