### ISSUE TITLE
extra .html in dirhtml project search results causing broken links

### ISSUE THREAD

**Issue by thomasgilgenast** [readthedocs/readthedocs.org#6801]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/lib5c
* Build URL (if applicable):
  - https://readthedocs.org/projects/lib5c/builds/10656892/
  - https://readthedocs.org/projects/lib5c/builds/10656858/
* Read the Docs username (if applicable): thomasgilgenast

## Expected Result

Links on the search results page (e.g., https://lib5c.readthedocs.io/en/latest/search/?q=qnorm&check_keywords=yes&area=default) should work. 

Since both the settings on the readthedocs project and the `.readthedocs.yml` file (the "latest" one is [here](https://bitbucket.org/creminslab/lib5c/src/0.6.0/.readthedocs.yml)) both specify that this project should be built in the `dirhtml` format, I expect the links to look like `.../<pagename>`, `.../<pagename>/`, or `.../<pagename>/index.html`.

## Actual Result

Links on the search results page look like `.../<pagename>.html` (they include an extra `.html`), as if the project was built in the `html` format, which causes them to 404.

I have wiped and rebuilt both of the builds linked above and the problem persists.

Locally building the docs with `sphinx-build -b dirhtml ...` leads to search results links that work as expected.

This issue doesn't impact all of my `dirhtml`-formatted projects, for example the project at https://readthedocs.org/projects/hic3defdr/ works as expected.

This seems like the opposite of #2596 in that a "workaround" is to copy the search result link and delete the extra `.html` from it.

The links on the project search results page (e.g., https://readthedocs.org/projects/lib5c/search/?q=qnorm) all work correctly.

Old-enough versions of this project (e.g., https://lib5c.readthedocs.io/en/0.5.5/search/?q=qnorm) do have correctly working links. In those old versions I did not yet use the `.readthedocs.yml` file but I did specify the `dirhtml` format in the readthedocs project settings.

**Comment by stsewd** [comment]
Found the problem. Looks like a sphinx bug (or a bug with our sphinx integration).

You can see the problem only in one project because it's installing the latest version of sphinx 
https://bitbucket.org/creminslab/lib5c/src/9de4840c5aa95cddd3f2606db2dbfbc43dbc53f4/setup.py#lines-13

The other project is installing an older version

https://github.com/thomasgilgenast/hic3defdr/blob/8ddfc06b2f4aa1fe77b6919a50c4be9d239c626d/docs/requirements.txt#L1

The problem is here

https://github.com/readthedocs/readthedocs.org/blob/24ca737e3f5c0df359801a8dede6519f67a70cb6/readthedocs/core/static-src/core/js/doc-embed/search.js#L80-L80

Sphinx is setting `FILE_SUFFIX` to `.html` on `dirhtml`, when it should be an empty string.

Looks related to https://github.com/sphinx-doc/sphinx/pull/7283

**Comment by thomasgilgenast** [comment]
Thanks for identifying the issue and for the fast PR! Sorry for not mentioning the difference in Sphinx versions - I had forgotten about the differences in how I declare the Sphinx version between the two projects.

**Comment by stsewd** [comment]
@thomasgilgenast the fix should be deployed now. I can see correct results now https://lib5c.readthedocs.io/en/stable/search/?q=norm&check_keywords=yes&area=default

(if you don't see them, try cleaning the cache from your browser)

**Comment by thomasgilgenast** [comment]
Thank you!
