### ISSUE TITLE
Make all tests pass with django_dynamic_fixture 3.x

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6886]
When updated ddf in https://github.com/readthedocs/readthedocs.org/pull/6885, a lot of tests started to fail... the reason? We are creating models with fields they don't have.. ddf is more strict now, that's good. I didn't want to expend more time in https://github.com/readthedocs/readthedocs.org/pull/6885 so I'm creating this issue to keep track of that.

**Comment by santos22** [comment]
What's the reason these are failing? Are they all failing for the same reason? I tried running some tests locally and the following was what I got:

```
tox -e py37 readthedocs/rtd_tests/tests/test_project_forms.py
```

<img width="1552" alt="Screen Shot 2020-05-05 at 10 42 37 AM" src="https://user-images.githubusercontent.com/7004949/81097787-3bb67d80-8ebd-11ea-8c92-a928efe3aa76.png">

This might be because I'm using py37.

**Comment by stsewd** [comment]
@santos22 we are creating some models with invalid data, django dynamic fixture used to just ignore that, but with the new version it raises an exception. The codebase should run with python 3.6.

You can see some corrections in https://github.com/readthedocs/readthedocs.org/pull/6885/files

**Comment by santos22** [comment]
Sounds good. I'll try to get this running with Python 3.6 and fix some of these tests.

**Comment by santos22** [comment]
Managed to get Python 3.6 running on my Windows machine. Working on making the tests pass 👍
