### ISSUE TITLE
users cannot customize notification message's format

### ISSUE THREAD

**Issue by bowenli86** [readthedocs/readthedocs.org#6942]
## Details

I want to use the notification webhooks feature, but my webhook expects a specific format, like 

```
{
   "msgtype": "text",
   "body" {
      ....
    }
}
```

Right now it seems I cannot do any customization

## Expected Result

Allow users to customize notification message in the "notification" page

## Actual Result

notification message is of fixed format

**Comment by humitos** [comment]
Hi @bowenli86! Thanks for opening this issue. Unfortunately, I don't think we will implement this. Sounds like a very user-specific request and you should be able to change the implementation on your end to accept and parse the format that RTD sends.

**Comment by bowenli86** [comment]
> Hi @bowenli86! Thanks for opening this issue. Unfortunately, I don't think we will implement this. Sounds like a very user-specific request and you should be able to change the implementation on your end to accept and parse the format that RTD sends.

Hi @humitos I'm not sure if it's a too user-specific request. The use case is that many chatbot webhooks on messaging platforms require some specific formats for various reasons. The limitation means I cannot send notifications to our chat apps.

**Comment by humitos** [comment]
I understand. You will need to put something between the RTD and the chatbot to parse RTD's webhook and convert it as the format required by the chatbot.

**Comment by ericholscher** [comment]
Seems we could pretty easily allow customizable keys on the JSON, but that's definitely a product decision we need to think about.

**Comment by devamchakrabarty** [comment]
Since the [homepage](https://docs.readthedocs.io/en/latest/index.html) asks us to `Think of it as Continuous Documentation`, we genuinely hope this feature request can gain some importance. 

We want to fit `documentation` as a step in our product's CI/CD pipeline. To do that, read the docs must at least allow the webhook JSON payload to be customisable. 🥺  

The [possibilities](https://api.slack.com/messaging/webhooks#advanced_message_formatting) are literally endless!

**Comment by ericholscher** [comment]
Interesting example here: https://twitter.com/mariatta/status/1278038611338772480
