### ISSUE TITLE
Hide unbuilt versions in the flyout

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#6971]
Currently we show links to docs in the flyout that have `built=False` in them. This leads to 404's. We should filter those out when showing the version list when we expect users to be able to view the docs.

**Comment by prashantmital** [comment]
Is there a way to disable this behavior? On https://pymongo.readthedocs.io/en/stable/ we relied on unbuilt versions showing up in the version picker. The 404s were worked around using a redirect to another website that hosted docs for those versions.

**Comment by stsewd** [comment]
No, you can't disable this behavior, I'm not sure if we want to support that use case (showing _fake_ versions). Maybe a better solution would be showing those versions in another page.

**Comment by prashantmital** [comment]
@stsewd thanks for the quick response. I'm surprised to learn that you have no plans to support this use-case especially since it seems like you are aware of it: https://github.com/readthedocs/readthedocs.org/issues/6137#issuecomment-528410245

**Comment by humitos** [comment]
@prashantmital Yeah. I'd like to reconsider this use case eventually and build a proper feature around it (instead of the "hidden feature" that I described in the linked comment). I know some people were using this already.

I'd suggest you to open a new issue as "Feature request" explaining your use case and linking the history around this. I don't think it will hit our roadmap soon though, but I'd like to see this feature to happen eventually. This is a good onboarding feature for people migrating their docs _into_ Read the Docs, which is :100: to us.
