### ISSUE TITLE
Version switcher points to URL ending in .html instead of URL without

### ISSUE THREAD

**Issue by marcelstoer** [readthedocs/readthedocs.org#7087]
I didn't find this reported anywhere in open or closed issues. However, it feels like such an obvious "bug" that it might very well be that _I_ am doing something wrong. Yet, I don't see how I could control the content of the version switcher.

## Details

* Read the Docs project URL: https://nodemcu.readthedocs.io
* GitHub repo: https://github.com/nodemcu/nodemcu-firmware
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

"Version" link in the version switcher component points to the correct deep link URL. For URL https://nodemcu.readthedocs.io/en/dev-esp32/modules/gpio/ selecting version `dev` it should point to https://nodemcu.readthedocs.io/en/dev/modules/gpio/

## Actual Result

It points to a URL ending in `.html`. The effective URL for the above example is thus https://nodemcu.readthedocs.io/en/dev/modules/gpio.html - a resource that is half-404: missing styles and other components.

<img width="724" alt="Screenshot 2020-05-07 at 22 18 53" src="https://user-images.githubusercontent.com/624195/82158747-febd9400-9889-11ea-8f5a-db2c2b10f6e1.png">

**Comment by humitos** [comment]
Hey @marcelstoer! Thanks for your report. This is definitely a bug in our side :cry: 

> Yet, I don't see how I could control the content of the version switcher.

Unfortunately, this is not currently possible. We are discussing about a complete refactor of that version selector by making it API driven, where the endpoint returns a JSON and it's built in the client side, instead of the server returning a HTML blob.

>  points to a URL ending in `.html`. The effective URL for the above example is thus https://nodemcu.readthedocs.io/en/dev/modules/gpio.html -

This is a bug. `dev` link should point to the correct URL _without_ the `.html` part in your case.

We handle different URLs for Sphinx `html` builder (with `.html`) and Sphinx `dirhtml` builder (without `.html`). I suppose we are doing something wrong when detecting the type of your project.

I'm seeing your project is built with MkDocs, and it seems the logic we use for Sphinx is not working in that case. I'll need to dig into the code a little more.

**Comment by stsewd** [comment]
Looks like this only affect old mkdocs projects only, new versions don't define

https://github.com/readthedocs/readthedocs.org/blob/8652573774a45bfb26c4de9d9bbed4dd52158e60/readthedocs/doc_builder/templates/doc_builder/data.js.tmpl#L14

so, we just always link to `/` for those

**Comment by marcelstoer** [comment]
That conditional `mkdocs_page_input_path` is something I proposed way back then to fix an issue on the search page. However, I don't understand

> Looks like this affects old mkdocs projects only

What does "old" in this context mean? Is there a way I can figure out what the highest/newest supported MkDocs version is?

**Comment by stsewd** [comment]
@marcelstoer I tested it with mkdocs 1.x and that var isn't defined, not sure since which version of mkdocs that was removed.
