### ISSUE TITLE
Project build step doesn't see READTHEDOCS environment variable

### ISSUE THREAD

**Issue by Zlopez** [readthedocs/readthedocs.org#7122]
## Details

To build the-new-hotness on the RTD, I added special function to [setup.py](https://github.com/fedora-infra/the-new-hotness/blob/master/setup.py) that is skipping the specific requirements if `os.environ.get("READTHEDOCS") == "True"`. But it looks like those packages are still installed and because pycurl doesn't work without `curl-devel` libs pre-installed it's failing to build. So I assume that the `READTHEDOCS` variable is not set or not available when project is build.

* Read the Docs project URL: https://readthedocs.org/projects/the-new-hotness
* Build URL (if applicable): https://readthedocs.org/projects/the-new-hotness/builds/11112007/
* Read the Docs username (if applicable): zlopez

## Expected Result

The documentation should be build without issue and skipping ignored packages based on the `READTHEDOCS` variable

## Actual Result

The documentation build fails, because the packages are not skipped

**Comment by stsewd** [comment]
This is happening because you are pinning your deps now https://github.com/fedora-infra/the-new-hotness/commit/1b91f60264164f13dc4d664e3d5da7e6ca36b7d5#diff-b4ef698db8ca845e5845c4618278f29a

But you are still checking for the exact name https://github.com/fedora-infra/the-new-hotness/blob/7c332a959acc44564b988ec5bccd38237cee48a7/setup.py#L45

**Comment by Zlopez** [comment]
Sorry for bothering you then, I started to use dependabot a few weeks ago and forgot that I started to use precise versions.

Thanks for investigating the issue. I will fix it.
