### ISSUE TITLE
Deleting account and then sign up with same email does not work

### ISSUE THREAD

**Issue by swati-rashmi** [readthedocs/readthedocs.org#7142]
I deleted my Github account.Now i want to use the same email with different username to create a fresh account.
But github says 'email invalid or taken'.I thinks my email address is not yet purged from DB.
Or does it take some time to reflect.

Can somebody help me with this.
Can my account be deleted swati-rashmi01

**Comment by davidfischer** [comment]
I don't see any Read the Docs account for `swati-rashmi01` and I don't see any account in our system linked with your github account.

This may require sending some private information such as the email address of your account to get this fixed. Feel free to email support@readthedocs.org instead of posting it here publicly.

**Comment by mynkydv09** [comment]
can i delete my github account and use the same email address for the new account?
