### ISSUE TITLE
Remove quiet mode for conda environment creation?

### ISSUE THREAD

**Issue by SylvainCorlay** [readthedocs/readthedocs.org#7238]
When using conda, RTD currently makes use of the `--quiet` option.

```
conda env create --quiet --name latest --file docs/environment.yml
```

In case of a build failure, it may actually be useful to access the logs and see the detailed versions that are being installed.

How about removing the --quiet option?

**Comment by humitos** [comment]
We use the `--quiet` version remove the progress bar that populates the output a lot and in most of cases it's not really useful. We already had a report to list the packages installed in a `conda` environment to do some debugging and because of that we added a feature flag, `LIST_PACKAGES_INSTALLED_ENV`, that can be enabled per-project by request. See https://docs.readthedocs.io/en/stable/guides/feature-flags.html#feature-flags

**Comment by stsewd** [comment]
Please let us know the name of your project on Read the Docs, so we can enable the flag for your project. Closing in favor of https://github.com/readthedocs/readthedocs.org/issues/7005
