### ISSUE TITLE
 Mamba usage to improve performance (memory & speed)

### ISSUE THREAD

**Issue by SylvainCorlay** [readthedocs/readthedocs.org#7239]
It may be interesting to experiment with mamba as an alternative to conda to spawn conda environment. Memory consumption and build times should be greatly reduced.

FYI, there was a blog post released about mamba recently, announcing the future plans for the project.

https://medium.com/@QuantStack/open-software-packaging-for-science-61cecee7fc23

**Comment by humitos** [comment]
Hi @SylvainCorlay! Thanks for sharing this. We already did some tests with Mamba and we got some good results (see #6815). We started doing that because we had memory issues with `conda`. However, now we have migrated to bigger servers and we are happy with the results. You can read more about this at https://blog.readthedocs.com/better-conda-support/

I'm still interested on merging the PR I linked here eventually, since it's under a feature flag and there are some improvements that I'd like to have, but since we don't have the problem anymore I prefer to keep it closed for now to avoid maintaining more code if it's not necessary.

**Comment by SylvainCorlay** [comment]
@humitos FYI MyBinder has switched to mamba, and it appears to be working well so far!

**Comment by astrojuanlu** [comment]
New micromamba docs: https://github.com/mamba-org/mamba/blob/master/docs/source/micromamba.md
