### ISSUE TITLE
Return relative URLs in indoc search results

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#7311]
This will save us one query for the domain, and also not change the current domain.

I think it makes sense to add it into the new api https://github.com/readthedocs/readthedocs.org/pull/7255/

**Comment by agjohnson** [comment]
It would be helpful to audit why we were requiring this on search results and if there is a strong reason (still?) to require the absolute URL. I'm assuming we did this because it was easiest to use our resolver to be able to support subproject results, which would trigger the domain part of the resolver as well. For most API interactions, perhaps what we really need is a URL path relative to the domain name used in the request.

**Comment by stsewd** [comment]
I think the main reason was we were hitting the API from readthedocs.org/api/, but now we are hitting the api from the same domain of the docs mydocs.readthedocs.io/_/api/docsearch/ (so this makes it more clear how to concatenate the results), and we were using the same code for the results from the dashboard. Subprojects share the same domain, so it shouldn't be a problem. We can also return canonical project domain in the api (as an extra field) just in case.
