### ISSUE TITLE
Run build on force-pushed tag

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7324]
Tags that are forcibly updated, should have a build ran on them again.

**Comment by Daltz333** [comment]
daltzprivate.readthedocs.io/

**Comment by Daltz333** [comment]
See the force-tag branch.

**Comment by Daltz333** [comment]
Not stale.

**Comment by JamesRandom** [comment]
I have reported this via support, as well. (I have now switched to using branches for versioning, because it seems to be more reliable)

**Comment by humitos** [comment]
@Daltz333 can you fill the issue with the template? Indicating your project URL, build URL, what you expect and what you got? What is the commit build on RTD and which one is the one that you were expected to be built? Thanks!

Also, can you verify that GitHub effectively sent the webhook to Read the Docs? Did Read the Docs received the webhook? What was its response? (you can check that from the Admin project's page).

**Comment by Daltz333** [comment]
I no longer have the project setup for force-pushing unfortunately and it's not trivial to reconfigure it.

**Comment by Daltz333** [comment]
I don't think this is necessarily stale.

**Comment by humitos** [comment]
I think we need more information to track this issue down. We need project already hitting this configured on Read the Docs were we can replicate the issue. I already requested this info in my previous comment. Without that info, I think we should close this issue.

**Comment by bwoodsend** [comment]
I'm probably chancing my luck hoping that I can necrobump this issue. I've got one: 

## Details

* Read the Docs project URL: https://readthedocs.org/projects/pyinstaller/
* Build URL (if applicable): https://readthedocs.org/projects/pyinstaller/builds/16742939/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/bwoodsend/

## Expected Result

Doing a git tag update (spelt out below just in case there's any uncertainty) should automatically rebuild the amended tag and serve it under `https://$site-url/$language/$tag`:

```
git tag x.y.z
git push --tags
# Oh dear! My docs are broken for some unrelated reason!
git commit -m 'Last minute docs fixup'
git tag -f x.y.z
git push -f --tags
```

## Actual Result

Readthedocs appears to have cached the commit hash corresponding to the tag so that triggering a build on the tag checks out the older commit instead of the new one. In my case, I'm trying to build docs for a `v5.0.1` release which should build https://github.com/pyinstaller/pyinstaller/commit/0de9d6cf1701689c53161610acdab143a76d40b5 but the build logs clearly indicate that it's stubbornly sticking to building https://github.com/pyinstaller/pyinstaller/commit/9cd95992503194f75f735a9e5949d8f19b386343.

**Comment by bwoodsend** [comment]
Ahh nice! Not only are my docs back online but you managed to fix it before the barrage of issues to tell me my docs links don't work.

Just to clarify, the workaround was to build the latest development branch (which makes it far enough through the pipeline to hit the _resyncronise tag->SHAs_ step) then rebuild on the tag, correct?

**Comment by stsewd** [comment]
> Just to clarify, the workaround was to build the latest development branch (which makes it far enough through the pipeline to hit the resyncronise tag->SHAs step) then rebuild on the tag, correct?

yes
