### ISSUE TITLE
Integration into Redirafe

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7497]
Hello ReadTheDocs Team,

My documentation team has developed a redirects extension that solves https://github.com/readthedocs/readthedocs.org/issues/6621. It'd be interesting to see what is required to integrate this on the ReadTheDocs side. ReadTheDocs could hook into the extension and dynamically traverse through the git history detecting renames each commit and use the rediraffe extension to link these into redirects on documentation generation. ReadTheDocs does automatic configuration automatically using the ``rediraffewritediff`` builder.

See https://github.com/wpilibsuite/sphinxext-rediraffe for more information.

**Comment by stsewd** [comment]
Looks like a useful tool, we are trying to build generic solution now than having something that only works for sphinx. So I think your tool could be used to generate new redirects locally and put them in the config file. Also, we do a shallow clone of repos, so that's another point to run the extension locally instead of in rtd.
