### ISSUE TITLE
Url ends with (.html) instead of "/"

### ISSUE THREAD

**Issue by imsahil007** [readthedocs/readthedocs.org#7529]
## Details

* While reading the documentation for some projects I noticed that the link for a lot of projects was broken.
* I found out that it same for a lot of projects where they used to use normal URL links without the HTML extension

## This works

https://warehouse.readthedocs.io/development/getting-started/

## This doesn't (Earlier it used to)
https://warehouse.readthedocs.io/development/getting-started.html

As a result of which the links for documentation of various Readme files are broken

**Comment by imsahil007** [comment]
Checkout this:
https://github.com/pypa/warehouse/pull/8656#issuecomment-703139824

**Comment by humitos** [comment]
I think your examples are interchanged. The one you said it doesn't work, works to me and viceversa :)

However, I'm not sure to understand what's the underlying issue here. The URL _without_ the `.html` extension is wrong, that's why it leads to a 404 page.

If you have changed your builder (Sphinx HtmlDir to Sphinx Html or viceversa) you can set a redirect to fix that. See https://docs.readthedocs.io/en/latest/user-defined-redirects.html#sphinx-redirects

That should solve your issue. Let me know if anything.

**Comment by imsahil007** [comment]
@humitos I did interchange the urls. Thanks for noticing that.
Changing Sphinx HtmlDir to Sphinx Html or vice-versa doesn't make any change. You can check the issue here. 
https://github.com/pypa/warehouse/pull/8656#issuecomment-703139824

**Comment by stsewd** [comment]
@imsahil007 you are using a config file, so all versions that have one will use the value from there https://github.com/pypa/warehouse/blob/master/.readthedocs.yml see https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx
