### ISSUE TITLE
Duplicate documentation is served when default branch is not named "master"

### ISSUE THREAD

**Issue by ZelnickB** [readthedocs/readthedocs.org#7533]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/aluminumjs/

I recently changed the default branch for my project to `main` (from `master`). I updated my settings on the Read the Docs admin dashboard (under **Advanced Settings**, I changed **Default branch** to `main`). Now, latest points to the build of the docs from my `main` branch, but under the **Versions** section, "main" is still listed as an inactive version; in addition, the main branch is being served separately (at https://aluminumjs.readthedocs.io/en/main/), even though it is identical to latest. This did not happen when `master` was my default branch.

**Comment by humitos** [comment]
> Now, latest points to the build of the docs from my `main` branch, but under the **Versions** section, "main" is still listed as an inactive version; 

This is the expected behavior.

> in addition, the main branch is being served separately (at [aluminumjs.readthedocs.io/en/main](https://aluminumjs.readthedocs.io/en/main/)), even though it is identical to latest. This did not happen when `master` was my default branch.

Have you activated `main`? That's why. You have the `latest` version pointing to `main` and _also_ `main` active. So there are two versions on Read the Docs serving the exact set of documentation: `latest` and `main`.

This probably didn't happen with `master` because you never activated that branch. If you de-activate `main` you will have the behavior you expect.

**Comment by ZelnickB** [comment]
On the versions page, `main` still has the activate button next to it, so I believe that it is not activated.

**Comment by ssolari** [comment]
@humitos I think it is important to note that ALL default branches from github for ANY project globablly are called 'main'.   I just tried to setup readthedocs on a new project and it failed.   I had to create a branch called 'master' because readthedocs is doing a '--force /master'.

Whether in this issue or another issue, I think RTD should fix the default clone to look for master OR main somehow.  All future projects that are created after Oct.1 2020 will have this problem.

**Comment by humitos** [comment]
>  I just tried to setup readthedocs on a new project and it failed. 

A project imported on RTD that only contains the `main` branch will fail with this error message:

```
$ git checkout --force master
error: pathspec 'master' did not match any file(s) known to git. 
```

> I had to create a branch called 'master' because readthedocs is doing a 'clone --force branch/master'.

There is no need to create a branch called `master`, you just need to change the "Default Branch" in your project's settings to `main` that will work.

> Whether in this issue or another issue, I think RTD should fix the default clone to look for master OR main somehow. All future projects that are created after Oct.1 2020 will have this problem.

I will open a new issue to track this. Thanks!

**Comment by stsewd** [comment]
I think we can solve this by allowing to set the default version at import time in the advanced menu, when importing from a VCS provider we could see if the default version is in the API so we just use that.
