### ISSUE TITLE
Increase concurency limit on project: frc-docs

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7551]
## Details

* Read the Docs project URL: frc-docs.readthedocs.io
* Read the Docs username (if applicable): Daltz333

## Expected Result

Our project has a vast number of momentum and PRs created, and the 2 build concurrency limit is hurting us, especially as it doesn't seem to retry. I seem to get a ton of duplicated builds if I merge PRs too fast

https://readthedocs.org/projects/frc-docs/builds/12056292/
https://readthedocs.org/projects/frc-docs/builds/12056298/

Phantom Triggers:
https://readthedocs.org/projects/frc-docs/builds/12056287/

A build that has never retried:
https://readthedocs.org/projects/frc-docs/builds/12056792/
![image](https://user-images.githubusercontent.com/10674555/95487726-b1d67900-0962-11eb-8e50-b264cca3745c.png)

Random Build Errors that are unrelated
https://readthedocs.org/projects/frc-docs/builds/12052148/

## Actual Result
Increased Concurrency Limit (5?), and more stability on retrying of limited builds

**Comment by humitos** [comment]
> I seem to get a ton of duplicated builds if I merge PRs too fast

The duplicated builds is a restriction that we added recently to avoid some sort of attack to our builders. _In theory_, it shouldn't affect your builds because a build is marked as duplicated if "there is already a build triggered for the same version and not finished". So, if you merge 4 PRs too fast, that will trigger 4 builds immediately for the `master` branch, but all of them would build the exact same commit of the documentation (latest commit on `master`). In that case, we mark 3 builds as duplicated and just build 1 with the latest commit merged on `master`.

> Phantom Triggers

This could be a build that failed for some unknown reason that we weren't able to catch and won't be retry. They will eventually be killed and marked as finished as failed.

> Random Build Errors that are unrelated

This could be a commit that was forced pushed and disappeared form the repository. See https://github.com/wpilibsuite/frc-docs/pull/875#event-3853430980

----

In general, have you experienced this too frequently lately or was this an isolated case? Does this happen only when you merge multiple PRs too fast?

**Comment by humitos** [comment]
> A build that has never retried:

This build was finally retried. https://readthedocs.org/projects/frc-docs/builds/12056792/

It seems that it was hitting the concurrency limit over and over again every 5 minutes :)

**Comment by Daltz333** [comment]
It's generally only when merging PRs too fast, which isn't uncommon.

**Comment by humitos** [comment]
Hi @Daltz333! I increased your concurrency limit to 4 for now. Let's see if that helps.
