### ISSUE TITLE
Redirects don't work if the url includes `/projects/foo`

### ISSUE THREAD

**Issue by ltalirz** [readthedocs/readthedocs.org#7552]
## Details

It seems that in exact redirects the $rest keyword is treated "verbatim" rather than as the placeholder it is intended to be. 

The [documentation](https://docs.readthedocs.io/en/latest/user-defined-redirects.html) on exact redirects explains

![image](https://user-images.githubusercontent.com/1053245/95608715-d3685b00-0a5d-11eb-8c85-16eafb1ba732.png)

So, I tried setting up the following redirect on the `aiida-core` RTD project:

![image](https://user-images.githubusercontent.com/1053245/95608759-e713c180-0a5d-11eb-8039-227fe15f7189.png)

## Expected Result

All requests of the form 
https://aiida-core.readthedocs.io/projects/abc
should be redirected to
https://aiida.readthedocs.io/projects/abc

## Actual Result

Only the "verbatim" request
https://aiida-core.readthedocs.io/projects/$rest
is redirected to
https://aiida.readthedocs.io/projects/

**Comment by humitos** [comment]
Hi! Thanks for your report. The `/projects/` part of the URL has a special meaning in Read the Docs and it's used to define _subprojects of a project_. In your example, `abc` is a subproject of `aiida-core`. Read the Docs tries to find the `abc` subproject and fails. That's why it's returning 404.

The code that produces this is at https://github.com/readthedocs/readthedocs.org/blob/2d64328ea88626925836e8cb8594a605c80cd3c4/readthedocs/proxito/views/decorators.py#L42-L46

That decorator is executed immediately when the page is tried to be served and the redirects code is not hit at all because the decorator fails: https://github.com/readthedocs/readthedocs.org/blob/2d64328ea88626925836e8cb8594a605c80cd3c4/readthedocs/proxito/views/serve.py#L72-L79

I'm afraid that this is a current limitation about how redirects with `/projects/` in the URL works.

> Only the "verbatim" request
> https://aiida-core.readthedocs.io/projects/$rest

This redirect works because `$rest` is interpreted as `''` (empty).

1. RTD tries to access `/projects/` page in a project with versions and it fails,

```
WARNING Invalid URL for project with versions. url=projects/, project=aiida-core [readthedocs.proxito.views.serve:122]
```

2. The 404 handler is triggered and found a redirect

```
Redirecting: from=https://aiida-core.readthedocs.io/projects/ to=https://aiida.readthedocs.org/projects http_status=302 [readthedocs.proxito.views.mixins:233]
```

(note that `$rest` does not appear in the `from=` URL)

**Comment by ltalirz** [comment]
Thanks a lot @humitos for the detailed analysis!

I see - I was trying to use the redirect in order to work around https://github.com/readthedocs/readthedocs.org/issues/7487 (i.e. to fix the broken links in the search results on `aiida-core`, which wrongly include the `/project` prefix).

This particular use case will go away once https://github.com/readthedocs/readthedocs.org/issues/7487  is fixed, but there is another use case that will remain: if a subproject moves away from a parent project, it would be very useful to be able to still redirect requests to a different documentation site.
I.e. thanks for accepting this as a feature request.
