### ISSUE TITLE
Notified of a failed build that does not exist

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#7587]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy/
* Build URL (if applicable): https://readthedocs.org/projects/astropy/builds/12149040/
* Read the Docs username (if applicable): pllim

## Expected Result

No notification about a failed build if the build succeeded.

## Actual Result

Got the following email notification but when I checked the build, it was successful (or in a previous occurence, still building). This is not the only time such a situation happened. It has happened with different build IDs in the past few days, but perhaps not for every build?

<hr/>

From: Read the Docs
Sent: Tuesday, October 20, 2020 8:51 PM
Subject: Failed: Astropy (f39a33a3)

Astropy build #12149040

Build Failed for Astropy (latest)

Error: There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (12149040).

You can find out more about this failure here:

[Astropy build #12149040](https://readthedocs.org/projects/astropy/builds/12149040/) - failed

If you have questions, a good place to start is the FAQ:

https://docs.readthedocs.io/page/faq.html

You can unsubscribe from these emails in your [Notification Settings](https://readthedocs.org/dashboard/astropy/notifications/)

Keep documenting,
Read the Docs

Read the Docs
https://readthedocs.org

**Comment by humitos** [comment]
Thanks for your report. I think I know what happened here. In some scenarios when the build fails (the process is killed for some reason and don't remove the celery task from redis), we retry it.

So, we probably sent the notification for the failed build. Then retry, and finally it succeeded. In fact, if you check the build output, you will see the `git clone` was done twice, that's because it failed immediately before the second `git clone` and we retry after that.

Unfortunately, we don't have a great solution for this yet.

**Comment by pllim** [comment]
Ah, thanks for the explanation! I am glad I am not going crazy over here.
