### ISSUE TITLE
Failed build email for successful build

### ISSUE THREAD

**Issue by plaindocs** [readthedocs/readthedocs.org#7627]
## Details

* Build URL (if applicable): https://readthedocs.org/projects/writethedocs-www/builds/12235484/

## Expected Result

Nothing

## Actual Result

![image](https://user-images.githubusercontent.com/95874/97800599-cdb5fd80-1c36-11eb-863f-98f7ceff154a.png)

**Comment by humitos** [comment]
Thanks for your report. This is a bug in our notification system.

Basically, if the build task is killed for any reason and we are not able to report back that the task finished (succeed or failed) we re-try the execution of the task. If you take a look at the build's output, you will see that there are some commands duplicated (eg. `git clone`). That's because the build was killed, and re-tried. The first time it was executed and failed, we notified you about the fail, but then we re-tried and it succeeded.

We need to find out a way to do not notify users if we are going to re-try the build.

**Comment by plaindocs** [comment]
Thanks @humitos ! :-)
