### ISSUE TITLE
RTD not recognizing new github branch

### ISSUE THREAD

**Issue by srcarter3** [readthedocs/readthedocs.org#7699]
## Details

* Read the Docs project URL:  https://readthedocs.org/projects/python-awips/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

I just recently created a new branch, 'rtd', on my github project (https://github.com/Unidata/python-awips/tree/rtd) and wanted to change the default branch in my readthedocs project to point to this new branch.  
The branch is not listed in the dropdown found in "Admin" > "Advanced Settings" > "Default Branch".
I set up a webhook as specified in the last comment on issue 4 - https://github.com/readthedocs/readthedocs.org/issues/4#issuecomment-578932267 and then pushed in a small change to trigger the webhook in readthedocs.

## Actual Result

I can see the webhook worked by going to "Admin" > "Integrations" and looking at my "Github incoming webhook" and it shows a "200" exchange with viable content in it, however when I go back to the "Default Branch" dropdown, I still don't see my new branch.

Any advice on how to get it to show up as an option?

Thank you.

**Comment by stsewd** [comment]
Hmm, I think for some reason the build wasn't triggered https://readthedocs.org/projects/python-awips/builds/, I have triggered a new build in order to refresh the versions. Your version should be listed here now https://readthedocs.org/projects/python-awips/versions/. In order to make it the default you'll need to activate it. If you see this happening again, let us know.

**Comment by srcarter3** [comment]
Thanks!  I see it in the list of branches now.
