### ISSUE TITLE
Not count traffic from the "maintainers of the project"

### ISSUE THREAD

**Issue by JuanDCG** [readthedocs/readthedocs.org#7711]
## Details

* Traffic analytics feature count traffic of the User-Agent of browser of the Maintainer, when the maintainer is login.

## Expected Result

* I'd like that my own traffic, as a maintainer, doesn't count in traffic analytics.

## Actual Result

* My own traffic count as visits.

**Comment by stsewd** [comment]
Currently, the endpoint to register page views is hosted on the same domain as the docs are served, so we don't have information about the current logged user there. In rtd for business we allow users to "log in" into that domain (via CAS), so there we do have that data. In order to implement this we would need to implement that logic here, but as the number of served docs from .org is huge, having authentication checks would increase the load, don't think this is worth it such complexity.

@readthedocs/core thoughts?

**Comment by ericholscher** [comment]
I'd love to add auth to the .org pages at some point, but it's definitely super heavy (and generally breaks the CDN) so we'd have to have a very good reason to do it. This is mostly an edge case, but we should likely support it on .com, given that we already have auth.

**Comment by JuanDCG** [comment]
I opened this issue because I detected this behavior, but only to suggest a possible improvement.

Besides, with new support of Google Analytics 4, the traffic analytics feature at .org have less importance. 

So, if it is a big change you can close the issue due to design core good reasons.

**Comment by stsewd** [comment]
Thanks for the suggestion anyway!
