### ISSUE TITLE
Dask-CUDA Excessive Memory Usage

### ISSUE THREAD

**Issue by quasiben** [readthedocs/readthedocs.org#7718]
## Details

* Read the Docs project URL: https://dask-cuda.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/dask-cuda/builds/12462341/
* Read the Docs username (if applicable): quasiben

## Expected Result

Successful build

## Actual Result

Build Error:
> Command killed due to excessive memory consumption

would it be possible to increase the memory limit ?

 Total download should be around  50 MB+.  I need both the `conda-forge` and the `rapidsai-nightly` channels to build the docs

**Comment by humitos** [comment]
The server instance where your build is run is using the maximum memory allowed :sweat: 

This a known issue in conda when using `conda-forge` channel, and in particular together with another one. See #7239 for some context on this topic (it has links to other previous issues and PRs)

I'm not sure if there is something immediate that we can do here, but I think the medium term solution is to support `mamba` at some point since it will mitigate this issue and improve all the build times.

**Comment by quasiben** [comment]
Thanks @humitos for the quick response.  I'll see if I can move things on my end

**Comment by humitos** [comment]
OK, I did a small trick and the build passed: https://readthedocs.org/projects/dask-cuda/builds/12463653/ --I force the upgrade of `conda` before the build starts. I don't know how long it will work anyways.

**Comment by quasiben** [comment]
Thanks @humitos.  I'll close this for now.  Thank you again for your time!
