### ISSUE TITLE
readthedocs.com : "This repository requires admin access to import" when trying to import project from GitLab

### ISSUE THREAD

**Issue by MajorSquirrelTVS** [readthedocs/readthedocs.org#7782]
## Details

As an organization, we're trying to use Readthedocs for Business to host our own documentation in a repository.

We're hosting on GitLab, we have a GitLab organization with sub-groups and few private projects per sub-groups. I have "Owner" role in the organization and also in sub-groups and projects.

On readthedocs.com we have created an Organization as well, I have "Admins" role in it and I have associated my GitLab account to my readthedocs.com account.

However, when trying to import any repository from GitLab, I am getting a message which says "This repository requires admin access to import" for every single project.

**Comment by humitos** [comment]
Hi @MajorSquirrelTVS! This issue should be solved already after deploying #7753. Are you still having this issue?

In any case, since you are using Read the Docs for Business, please contact us at support@readthedocs.com telling us what's your organization, project and username. We don't use GitHub issues as a support channel. Thanks!

**Comment by MajorSquirrelTVS** [comment]
Works like a charm now, thanks !
