### ISSUE TITLE
Running out of memory when building html files

### ISSUE THREAD

**Issue by CalebBell** [readthedocs/readthedocs.org#7788]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/fluids/
* Build URL (if applicable): https://readthedocs.org/projects/fluids/builds/12651345/
* Read the Docs username (if applicable): CalebBell

I made a small configuration switch to my project to render math equations using the [sphinxcontrib-katex](https://github.com/hagenw/sphinxcontrib-katex) sphinx extension. This project has a configuration option to generate all of the equations server side; I turned it on to speed up page loads. I did some testing on my machine and it cuts load time down by ~30%. However, the memory used and/or the time taken now seems to be too high for readthedocs.

Thank you all for the incredible service you provide, and Happy New Year!

## Expected Result

The build to finish successfully.

## Actual Result

```
reading sources... [ 91%] fluids.two_phase

Command killed due to excessive memory consumption

```

At the tops of the page, there is also the warning:

```
Error
Build exited due to time out
```

**Comment by humitos** [comment]
Hi @CalebBell! I increased the build time for your project (1200s) and triggered a new build at https://readthedocs.org/projects/fluids/builds/12654109/

I'm closing this issue, but feel free to re-open if it's not fixed yet. I can increase the time a little more or move your project to another bigger VM.

**Comment by humitos** [comment]
Hrm... I increased the time to 1800s and it's still failing. I now increased the build time to 2700s (45m) which _a lot_ and triggered another one https://readthedocs.org/projects/fluids/builds/12654394/

I suggest you to find a workaround for this because I don't think we can give ~1h building time to a single project.

As a reference, previous builds were taking about ~300s, https://readthedocs.org/projects/fluids/builds/12622919/

**Comment by humitos** [comment]
It finally took 2188s.

If I understand correctly, sphinxcontrib-katex is to render math formulas as a replacement for mathjax. IMHO, going from 300s to 2200s on each build just for that is not good --considering that rendering a math formula client side is super fast.

I think it makes sense to open an issue in that extension to mention this because it doesn't sound good that increase in build time just because of the formula rendering, or it may be a different problem.

**Comment by CalebBell** [comment]
Hi Manuel! Thank you for your kind and very helpful support. Yes, the time increase is very much not good. I didn't know it was this bad!

I have never had issues before but this really is a huge increase and I don't like waiting for builds. I was able to find the "root cause" in the extension, but addressing it requires substantial re-architechting of the extension. I have [let the author of the extension know about the limitation](https://github.com/hagenw/sphinxcontrib-katex/issues/37). 

I have turned the pre-rendering until a performance improvement can be made!
