### ISSUE TITLE
MkDocs: remove `mkdocs.yml` manipulation

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#7844]
We're currently parsing mkdocs YAML, which has some issues. This is an OK solution in the short term. In the longer term, we'd really love to not do any YAML parsing/dumping, and instead find a better way to integrate with mkdocs via an extension, or some other way that isn't so error-prone.

The main reason we are doing this currently is to add some small things to the config file. We should research and find another way of handling this, probably talking with the mkdocs team to ensure it will be supported going forward.

We merged a custom YAML parser in https://github.com/readthedocs/readthedocs.org/pull/7507, but we should plan to remove it and integrate in a way that doesn't require complex YAML.

**Comment by stsewd** [comment]
I created an issue related to this (or the same?), about creating an extension for mkdocs https://github.com/readthedocs/readthedocs.org/issues/4924

**Comment by humitos** [comment]
> The main reason we are doing this currently is to add some small things to the config file. We should research and find another way of handling this, probably talking with the mkdocs team to ensure it will be supported going forward.

We do this because we want to:
* inject JS and CSS files
* set _our_ theme by default
* inject Google Analytics code

The code that performs these actions is at https://github.com/readthedocs/readthedocs.org/blob/37650de695dff4bd2e80fd957974959ca9379307/readthedocs/doc_builder/backends/mkdocs.py#L143-L245

Note that _none of these 3 actions_ will be required anymore, so we will be able to remove the manipulation of the YAML completely. I wrote a more extended comment in https://github.com/readthedocs/meta/issues/85#issuecomment-1616690964 that also touches this topic.

**Comment by ericholscher** [comment]
> Note that none of these 3 actions will be required anymore, so we will be able to remove the manipulation of the YAML completely. I

Wonderful ❤️

**Comment by humitos** [comment]
Closing in favor of https://github.com/readthedocs/addons/issues/72
