### ISSUE TITLE
Build termninated due to inactivity #13136208

### ISSUE THREAD

**Issue by samukweku** [readthedocs/readthedocs.org#7972]
## Details

* Read the Docs project URL: https://github.com/ericmjl/pyjanitor
* Build URL (if applicable): https://readthedocs.org/projects/pyjanitor/builds/13146742/
* Read the Docs username (if applicable): samukweku

## Expected Result
Build should complete

## Actual Result
Build terminated due to inactivity

![readthedocs](https://user-images.githubusercontent.com/25709809/109646325-2a590300-7bac-11eb-8436-17c12054973d.png)

Not sure why it failed. Please help in resolving this issue.

**Comment by ericmjl** [comment]
For context, I think the build stopped at the command `cat latexmkrc`. At least, it's consistently stopped there.

**Comment by humitos** [comment]
@ericmjl can you put the build URL in the description?

Also, did you receive this error multiple times or it was just this time?

**Comment by samukweku** [comment]
@humitos updated the build url. And yes, the error occurs multiple times

**Comment by stsewd** [comment]
The build is stuck at the build pdf step, when a build fails we don't save that command, that's why the last command that is shown is cat, I think this may due the notebooks https://github.com/ericmjl/pyjanitor/tree/dev/examples/notebooks maybe something there is taking a lot of time to render into pdf. If you don't need the pdf you can disable that format by using a config file https://docs.readthedocs.io/en/stable/config-file/v2.html (the formats key)

You can also try debugging this locally by generating a pdf with the same steps shown on rtd and see where is taking too long.

**Comment by ericmjl** [comment]
The PDF wasn't necessary, so we ended up taking off the PDF build.
