### ISSUE TITLE
Build: expose env var with the full URL from the current version

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#8260]
We expose some env vars in our builds https://docs.readthedocs.io/en/stable/builds.html#build-environment, I think it should be useful to add a `READTHEDOCS_VERSION_URL` or similar. (think we add the full url in the sphinx context, but having an env var would be more general)

Ref https://github.com/readthedocs/readthedocs.org/issues/8256#issuecomment-860795319

**Comment by mootari** [comment]
This would be really great to have. What open problems / questions are currently blocking this issue?

**Comment by humitos** [comment]
Hi @mootari! Can you comment here what's the use case you want to handle? I'm curious about how people will use this value.

Also, note there is a current workaround for this that's linked in the description of this issue. That may solve your case for now.

> What open problems / questions are currently blocking this issue?

I don't think there is anything blocking this, but it hasn't been a priority for our roadmap and we haven't had the time to implement it.

**Comment by mootari** [comment]
@humitos The [ddev](https://github.com/drud/ddev) project uses `mkdocs` in combination with the [Material theme](https://github.com/squidfunk/mkdocs-material). The theme requires a proper `site_url` in `mkdocs.yml`, otherwise its error page is completely broken (wrong resource paths, invalid relative navigation links on error pages).

Since mkdocs now supports [environment variables in its config](https://github.com/mkdocs/mkdocs/issues/1954), the last missing piece for a straightforward fix of the above problem would be an env var that provides the entire path, since multiple YAML tags / env vars cannot be concatenated.

Related issue: https://github.com/drud/ddev/issues/2939
