### ISSUE TITLE
Update MkDocs guide?

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8279]
The only MkDocs-specific guide we have on our documentation is this one:

https://docs.readthedocs.io/en/stable/guides/mkdocs-old-versions.html

However, it feels weird keeping it around, since MkDocs 1.0 was released 3 years ago https://www.mkdocs.org/about/release-notes/#version-10-2018-08-03

Perhaps we can focus on 1.1 vs 1.2? Or just make it more generic.

**Comment by humitos** [comment]
The linked documentation page gives 404 😞 

In any case, we have updated the "Getting started with MkDocs" some time ago (https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html). I just followed the steps and they work fine.

I think it's fine to close this issue now. Let me know otherwise.
