### ISSUE TITLE
[Discussion] in sktime repo, a HTML page not being rendered built on top of readthedocs on the live server

### ISSUE THREAD

**Issue by afzal442** [readthedocs/readthedocs.org#8350]
## Details

When I try to run my HTML page on a **live/local server**, it works but seeing it on `https://xyz.org.readthedocs.build/`, it doesn't. I couldn't find the difference and why it fails. e.g., I tried running on my local server i.e. http://127.0.0.1:5500/docs/built/estimator_overview.html, it worked whereas, on https://sktime--930.org.readthedocs.build/en/930/estimator_overview.html, it didn't.

I want to be clarified if it is only due to readthedocs ext and if it works on `https://xyz.org` after it is merged.

Plz, find the PR where we are working on is [pr-930](https://github.com/alan-turing-institute/sktime/pull/930).

## Expected Result

It should work on every server.

## Actual Result

Unexpected result **page not found.**

**Comment by astrojuanlu** [comment]
Hi @afzal442 , hello from the SciPy 2021 sprints! I'm having a look at this 👀

**Comment by astrojuanlu** [comment]
I'm not sure what extra steps we would need to make the approach in https://github.com/alan-turing-institute/sktime/pull/930 work on Read the Docs, since you are generating an extra HTML page and https://sktime--930.org.readthedocs.build/en/source/estimator_overview/estimator_overview_table.html is not found. Not saying it's impossible, just that I would need to look at it more closely.

The good news is that https://github.com/alan-turing-institute/sktime/pull/1138 by @mloning takes an approach that is more compatible with how things work in RTD, and I made it work locally including the filtering. Will leave a comment there soon.

**Comment by astrojuanlu** [comment]
https://github.com/alan-turing-institute/sktime/pull/1153 fixes the original issue 🚀 I'm leaving this open so I can investigate if your original idea is possible on RTD.

**Comment by afzal442** [comment]
Thanks, Juan Luis for your kind support and quick investigation. LGTM!
> I'm leaving this open so I can investigate if your original idea is possible on RTD.

Sure! We need you further if you can.

**Comment by afzal442** [comment]
hi @astrojuanlu, any update on this?

**Comment by humitos** [comment]
It seems the original issue was fixed in https://github.com/readthedocs/readthedocs.org/issues/8350#issuecomment-881891481
