### ISSUE TITLE
can't use `/en/` or `/zh/` as path prefix with single version

### ISSUE THREAD

**Issue by trim21** [readthedocs/readthedocs.org#8399]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sci-hub-p2p/builds/
* Build URL (if applicable): https://readthedocs.org/projects/sci-hub-p2p/builds/14416637/
* Read the Docs username (if applicable): trim21

( I replace the `en` with `_en` in the latest build, but older build are broken)

## Expected Result

URL like `domain/en/introduction.html` should works fine.

## Actual Result

all URL like `/en/introduction.html` or `/zh/introduction.html` prefix get 404

but url `/en/extra/index.md` works fine.

**Comment by stsewd** [comment]
Thanks for reporting, this is a current limitation from our code that serves the documentation, since we try to map the URL to the correct version/translation/subproject instead of using the project information to map that URL to a correct file. I put some comments on an alternative implementation for our serve code that could fix this kind of problems https://github.com/readthedocs/readthedocs.org/pull/8327

**Comment by stsewd** [comment]
Our new implementation of the code that serves documentation doesn't have this problem, the new implementation is under a feature flag, but we won't be able to support this case till we make remove the old implementation, specifically this

https://github.com/readthedocs/readthedocs.org/blob/eadf6ac6dc6abc760a91e1cb147cc3c5f37d1ea8/readthedocs/proxito/urls.py#L163-L171
