### ISSUE TITLE
Build error with build id #14658829

### ISSUE THREAD

**Issue by pradyunsg** [readthedocs/readthedocs.org#8474]
## Details:

* Project URL: https://readthedocs.org/projects/pip/
* Build URL(if applicable): https://readthedocs.org/projects/pip/builds/14658829/
* Read the Docs username(if applicable): pradyunsg

## Expected Result

The build should have passed?

## Actual Result

The build failed, despite the PR not touching any documentation.

**Comment by astrojuanlu** [comment]
Perhaps a temporary glitch? I see that, after closing and reopening the PR, build https://readthedocs.org/projects/pip/builds/14660797/ passed.

On the other hand, I don't see the "Rebuild this build" button. It would be nice to have it even in "weird" cases like this.

**Comment by humitos** [comment]
He he! I may be able to give some better information later...

![Screenshot_2021-09-08_12-39-59](https://user-images.githubusercontent.com/244656/132494910-ed26e760-e0c7-4727-a764-8718daa7e89c.png)

... Sentry is not being too useful.

**Comment by astrojuanlu** [comment]
Any clue of what happened here? Or should we just close this issue with `status:¯\_(ツ)_/¯`? :)

**Comment by stsewd** [comment]
This looks like a temporal error, think we can close

**Comment by astrojuanlu** [comment]
Similar to #8482

**Comment by humitos** [comment]
OK, this is sad 😢 

Sentry is still failing with "Internal Error". Besides, our internal logs for the builders are gone because our own logging was failing due to `rsyslog` behaving unexpectedly 🙃 

So, I don't have too much context to provide here and I'd say "It was a temporal error" and move on 😄 . In particular, because I don't see any other build failing in the first 10 pages.
