### ISSUE TITLE
'generator' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by ymarcon** [readthedocs/readthedocs.org#8663]
Hi,

2 weeks ago the build was passing like a charm:
https://readthedocs.org/projects/obiba-opal/builds/15094617/

The very same base code now fails with error `'generator' object has no attribute '__getitem__'`:
https://readthedocs.org/projects/obiba-opal/builds/15232225/

Do you have an idea why this happens?

**Comment by astrojuanlu** [comment]
Hi @ymarcon, looks like the first build has docutils 0.17 and the second one docutils 0.18, so the issue has probably the same root cause as sphinx-doc/sphinx#9834, sphinx-doc/sphinx#9811, sphinx-doc/sphinx#9810, sphinx-doc/sphinx#9809, sphinx-doc/sphinx#9727, sphinx-doc/sphinx#9788, readthedocs/readthedocs.org#8616 , readthedocs/readthedocs.org#8618, readthedocs/readthedocs.org#8640, readthedocs/readthedocs.org#8642. You can solve this by capping docutils to <0.18 in your requirements. More information here: https://blog.readthedocs.com/build-errors-docutils-0-18/

Finally, I would encourage you to migrate your documentation to Python 3. You can do so using the new v2 configuration files, see https://docs.readthedocs.io/en/stable/config-file/v2.html for reference.

**Comment by ymarcon** [comment]
Thanks for the tip! I will migrate to Py3 as well.
