### ISSUE TITLE
[FR] Add username in projects url to allow projects with same name

### ISSUE THREAD

**Issue by rockandska** [readthedocs/readthedocs.org#8686]
Didn't find an already submitted issue regarding this, but it would be very convenient to have the `user` include in projects url to don't be confronted to `project already exists` and lets users have their own project url in the same way work most of VCS.

Regards,

**Comment by stsewd** [comment]
Hi, the slug is used to serve the docs from `slug.readthedocs.io`, most users want to have that as the name of their project (which is usually used in other sites). You can change the project name to prefix your username already. I'd be -1 on doing this by default as it will create a project with an unexpected slug.

On readthedocs.com we do prefix the name of the organization, but the use case is a little different, as users will expose their docs using a custom domain instead of using the default provided (slug.readthedocs-hosted.com).

**Comment by humitos** [comment]
👍🏼 to what Santos says. Read the Docs Community uses a shared namespace (which is not necessarily tied to Python projects/packages --which is sometimes confusing as well) and I don't think we will change that since it's on the core of its functionality.

Soon, for some definition of it 😁 , we will introduce _organizations_ to Read the Docs community, but I don't think they will affect projects slugs as they are in Read the Docs for Business. They will probably be a way to group projects altogether to manage permissions and others, but may not have any effect on the slug's uniqueness.
