### ISSUE TITLE
Strange behaviour of environment vars

### ISSUE THREAD

**Issue by OriolAbril** [readthedocs/readthedocs.org#8722]
## Details

I added an html template that takes some variables defined in `html_context` dict of `conf.py` and generates github, binder and colab badges for posts generated from notebooks. Here are the relevant lines:

https://github.com/OriolAbril/pymc-examples/blob/574958a19822aa2624ce2add516039826173e398/examples/conf.py#L69-L77

The badges and links work perfectly for `latest`, generated from the `main` branch but they break when generating PR previews, which is confusing. 

I have tried to reproduce it in a minimal repo, but have not yet been able to reproduce it and don't really know what else to try. I have tried to reproduce it in https://github.com/OriolAbril/sphinx-playground/tree/rtd_myst_substitutions, where https://oriol-sphinx-playground--1.org.readthedocs.build/en/1/, https://oriol-sphinx-playground.readthedocs.io/en/rtd_myst_substitutions/ and https://oriol-sphinx-playground.readthedocs.io/en/rtd-myst-substitutions/ (example with dashes) are all working. 

So I have also tried a "debugging preview" that prints the conflicting variables which is much more convenient than checking the html links: https://pymc--252.org.readthedocs.build/projects/examples/en/252/generalized_linear_models/GLM-hierarchical-binomial-model.html (see below for relevant exerpt from this page)

I am not even 100% sure this is due to readthedocs completely but so far it's the only place where anything of the sort has happened and I am quite lost. 

## Expected Result
The links in the badges point to main given that the `READTHEDOCS_VERSION` variable is the PR number for which the preview is being generated and has no dashes in it.

In the "debugging preview" that would mean all bullet points end with `main`, no commit hash nor PR number.

## Actual Result

Even though the variables in the html context `github_version` and `sandbox_repo` are defined in `conf.py` using the same `version` variable, the first ends up containing the commit hash while the other has `main` as expected. Note that if there were an issue with the if/else logic, I would expect the variable to be "" or the PR number (which is what I see as version in the raw construction logs), I hve no idea how the commit hash end up in the mix. 

Here is what ends up happening in the "debugging preview":

```

    github_version: 574958a19822aa2624ce2add516039826173e398
    sandbox_repo: pymc-devs/pymc-sandbox/main
```

**Comment by stsewd** [comment]
Hi, this is happening because we inject our own context, this overrides the existing one.

You can see this on the build page https://readthedocs.org/projects/pymc-examples/builds/15393468/ (searching for `github_version`.

I have added the `DONT_OVERWRITE_SPHINX_CONTEXT` feature flag https://docs.readthedocs.io/en/stable/feature-flags.html to your project.

I'm not sure where we ended up with that feature, if it should be the default or if there was another plan  /cc @humitos

**Comment by OriolAbril** [comment]
Thank you so much :pray:! I was not aware of that. 

> I'm not sure where we ended up with that feature, if it should be the default or if there was another plan /cc @humitos

Depending on what the plan is I can help a bit, for example trying to document and increase awareness on this. i.e. we use the pydata-sphinx-theme which looks like a recipe for disaster when combined with this rtd feature if using the ["edit this page" button](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#add-an-edit-this-page-button) `github_version` is then, similarly to my situation used, for both branch name and commit hash at the same time.

**Comment by humitos** [comment]
> I'm not sure where we ended up with that feature, if it should be the default or if there was another plan /cc @humitos

I think we never enabled it by default because it hasn't produced enough issues for projects and we weren't sure it will always work when making it the default. However, we could probably enable it for new projects only and gather some data.

We could also review some of the conversations we have had before about this topic and refresh our memory a little. However, I don't think it is worth the effort at this moment. On the other hand, we do have a card to include the feature flags as product configurations. So, we will follow these there. I'm closing this issue since the reported problem was solved.
