### ISSUE TITLE
RTD PR builds get stuck

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#8772]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy/
* Build URL (if applicable): https://readthedocs.org/projects/astropy/builds/15566029/
* Read the Docs username (if applicable): pllim

## Expected Result

Build to run after "concurrency limit" is gone.

## Actual Result

The job got stuck at "triggered (Concurrency limit reached (2), retrying in 5 minutes.)" state for many hours. cc @astrojuanlu 

![IMG_20211217_193722](https://user-images.githubusercontent.com/2090236/146593018-2e7be4c4-27b7-46ba-9c3c-17f13e27c4ea.jpg)

I tried to close and re-open astropy/astropy#12587 in the hope to get past that roadblock but the new job won't start because it is marked as "duplicate".

Hope you can help. Thanks!

**Comment by astrojuanlu** [comment]
I'm away from keyboard now but indeed this looks like some sort of weird race condition to me. I recall that it has happened to other projects in the past.

**Comment by astrojuanlu** [comment]
After some time, the builds ended up passing:

![IMG_20211218_080244](https://user-images.githubusercontent.com/316517/146632633-dfdb1f26-d253-4d28-bf4c-eef49f54b933.jpg)

So, one could say that "everything worked as expected", but it is still not clear to me what was the second build that was supposedly running.

In any case, I believe the solution here would have been to cancel the running and queued builds and start again. we could do to mitigate this:

- Allow users to cancel builds that haven't started yet
- Give more information in the message (which build

**Comment by astrojuanlu** [comment]
Found the issue: #7660 (also opened by @pllim)

**Comment by humitos** [comment]
I think this problem is related to https://github.com/readthedocs/readthedocs.org/issues/4386.

We have a task that checked for blocked/invalid/ghost builds and cancel them. Those blocked/invalid/ghost builds are builds that for some reason failed but we weren't able to detect, so we think they are still "running". The task checks for "running" builds and kill those that have been running for a long long time --in the meanwhile, new builds may be blocked and that's why you get the ⚠️ icon in the build list. Once these ghost builds are killing, your quota is freed up and you are able to run a build again.

I tried to solve this problem by detecting those ghost builds earlier and kill them in https://github.com/readthedocs/readthedocs.org/pull/8269 but it requires more testing to be trustable.
