### ISSUE TITLE
Some UI settings override config file settings

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8782]
See for instance:

- Build: https://readthedocs.org/projects/ccdproc/builds/15588226/
- Config: https://github.com/mwcraig/ccdproc/blob/e7f919d4f6985208b495d3ab53c584f4e4410f14/.readthedocs.yml

Even though the config file does _not_ define [`python.system_packages`](https://docs.readthedocs.io/en/stable/config-file/v2.html#python-system-packages) and therefore should use the default value of `False`, the virtual env was created with `--system-site-packages` because the option was set in the UI.

@readthedocs/backend is this intended? I'm wondering if it happens with other settings as well.

**Comment by astrojuanlu** [comment]
cc @mwcraig @pllim

**Comment by pllim** [comment]
Thanks for following up on this, @astrojuanlu !

**Comment by humitos** [comment]
> @readthedocs/backend is this intended? I'm wondering if it happens with other settings as well.

This is not intended. In fact, we have a paragraph saying exactly this in the "Advanced settings" (`https://readthedocs.org/dashboard/ <your-project-slug> /advanced/`)

>  These settings can be configured using a configuration file. That's the recommended way to set up your project. Settings listed here are ignored when using a configuration file. 

This is a bug to me.

**Comment by humitos** [comment]
I opened #8783 to demonstrate this case with a test case and I think I found the issue after that. The config file code is not trivial to follow but I think the defaults we are passing are not correct because they are based on the `project` object (with settings defined in the Admin) instead of the defaults documented in the documentation of the config file.
