### ISSUE TITLE
Build failed: Could not find a version that satisfies the requirement pip==21.3.1

### ISSUE THREAD

**Issue by annagorlova** [readthedocs/readthedocs.org#8867]
Hi there,

https://readthedocs.org/projects/diadoc-sdk/builds/15936026/

`ERROR: Could not find a version that satisfies the requirement pip==21.3.1 (from versions: 0.2, 0.2.1, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.8.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.2, 1.2.1, 1.3, 1.3.1, 1.4, 1.4.1, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 6.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.1.0, 6.1.1, 7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.1.0, 7.1.1, 7.1.2, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.1.0, 8.1.1, 8.1.2, 9.0.0, 9.0.1, 9.0.2, 9.0.3, 10.0.0b1, 10.0.0b2, 10.0.0, 10.0.1, 18.0, 18.1, 19.0, 19.0.1, 19.0.2, 19.0.3, 19.1, 19.1.1, 19.2, 19.2.1, 19.2.2, 19.2.3, 19.3, 19.3.1, 20.0, 20.0.1, 20.0.2, 20.1b1, 20.1, 20.1.1, 20.2b1, 20.2, 20.2.1, 20.2.2, 20.2.3, 20.2.4, 20.3b1, 20.3, 20.3.1, 20.3.2, 20.3.3, 20.3.4)
ERROR: No matching distribution found for pip==21.3.1`

This build was successfull for 2 day ago. Currently, this build was failed.
What should I do for successful build?

**Comment by humitos** [comment]
Hrm... This is a problem introduced in #8865 with Python2.7 --which is deprecated. We may need to do some extra work on the Python2.7 case.

Since we are already talking about this, are you using Python2.7 for a particular reason? Note that Python 2.7 reached the end of its life on January 1st, 2020. I really recommend you to upgrade to Python 3 if that's possible. Otherwise, you will keep hitting issues like this one.

**Comment by annagorlova** [comment]
I have change Python version from 2 to 3 in my project, and it work. But it still looks as incorrect behavior for Python 2.7.

**Comment by humitos** [comment]
We solved this problem and we plan to deploy it later today.
