### ISSUE TITLE
Read the Docs Search

### ISSUE THREAD

**Issue by mohamedgaliaa** [readthedocs/readthedocs.org#8923]
## Details

* Read the Docs project URL: https://sdk-docs.dataloop.ai/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/dtlpy/builds/15940742/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/mohamedgaliaa/

## Expected Result

the search doesn't work form the first time

## Actual Result

when make search to get the result from the first time

**Comment by stsewd** [comment]
Hi, I think this is probably related to https://github.com/dataloop-ai/dtlpy/blob/6003cfffd6bc2e579d249d67345c0025d905ad58/docs/_templates/layout.html#L4-L6, when you replace the content of the DOM, you are also removing any reference to the old nodes. Looks like the order the functions are executed isn't deterministic, that's why it works sometimes.
