### ISSUE TITLE
Can't set "Default branch" after converting repo from hg -> git

### ISSUE THREAD

**Issue by ahal** [readthedocs/readthedocs.org#9108]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/taskcluster-taskgraph/

This project recently moved from Mercurial -> Git. But when I switched the repository type in the settings, the branch dropdown under [advanced](https://readthedocs.org/dashboard/taskcluster-taskgraph/advanced/) is still displaying the values for Mercurial (e.g `default`). I have no option to change my branch to `main` and then builds fail because rtd defaults to `master`.

## Expected Result

Default branch drop down should update to reflect repository type changes.

## Actual Result

Default branch drop down does not update to reflect repository type changes.

**Comment by ahal** [comment]
I may try deleting and re-creating the project if there is no other workaround here (hopefully that doesn't cause namespace issues).

**Comment by puttehi** [comment]
Have a possibly related issue: 
![image](https://user-images.githubusercontent.com/19575408/203553163-2ee3369c-5367-47e8-824f-f4db8188afb3.png)

Created the project with default, from GitHub, assuming it would pick up `main` but tries to build `master`. Why is this a dropdown instead of a text box in the first place?

**Comment by humitos** [comment]
@puttehi 

> Created the project with default, from GitHub, assuming it would pick up `main` but tries to build `master`.

As a workaround for now, you can delete and re-create the project specifying `main` as the default branch.

**Comment by humitos** [comment]
@ahal we deployed https://github.com/readthedocs/readthedocs.org/pull/9424 which is a potential fix for this. Would you please try this case again and let us know if it's solved now?

**Comment by SethMMorton** [comment]
If the fix is supposed to auto detect that a repository changed their default branch on GitHub from "master" to "main" and then provide "main" as a dropdown option instead of "master", then no, it does not appear that the change fixed that. I still see "master" instead of "main" as a build option.

![image](https://user-images.githubusercontent.com/1596189/216089810-15d79050-d261-4d62-abdd-5e61cd9c742a.png)

**Comment by humitos** [comment]
@SethMMorton No, the fix is not being blocked without being able to build a version properly. The `git clone` command should not fail immediately saying that the `master` branch was not found. _Only_ if the "Default branch" is not defined (i.e. `-------`) in you project's settings.

**Comment by humitos** [comment]
This issue seems solved already. If you consider it's not, please let us know what's missing from our side and feel free to re-open it.

**Comment by carlocagnetta** [comment]
> Have a possibly related issue: ![image](https://user-images.githubusercontent.com/19575408/203553163-2ee3369c-5367-47e8-824f-f4db8188afb3.png)
> 
> Created the project with default, from GitHub, assuming it would pick up `main` but tries to build `master`. Why is this a dropdown instead of a text box in the first place?

I still have the exact same issue actually. Was the fix released?
