### ISSUE TITLE
Old Pull Request previews are infinite redirecting

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#9109]
This is an outcome of #9048, but we need to figure out how to solve this issue. We could special-case `external` versions to avoid this logic, or the PR build domain, but I think we probably need to think a bit more about this issue. 

We do note that this should continue to work in the docs:

> The built documentation is kept for 90 days after the pull request has been closed or merged.
> https://docs.readthedocs.io/en/latest/pull-requests.html#limitations

Example: 
 * Documentation: https://docs--9104.org.readthedocs.build/en/9104/
 * Closed PR: #9104

**Comment by humitos** [comment]
We are currently marking external versions as `active=False` when the PR got closed/merged at

https://github.com/readthedocs/readthedocs.org/blob/ccdad233cda5bcd3ac3acd935536c9e8cfc2e440/readthedocs/core/views/hooks.py#L186

Then, we have a Celery task that collects external versions that are `active=False` and `modified_lte=90 days ago` at

https://github.com/readthedocs/readthedocs.org/blob/ccdad233cda5bcd3ac3acd935536c9e8cfc2e440/readthedocs/builds/tasks.py#L231

So we could:

1. change this logic adding a new field `Version.state=['open', 'closed', 'merged']` to track the state and know _when_ we have to delete these versions from the Celery task
2. exclude external versions that are `active=False` from the proxito logic
3. exclude the PR domain from the proxito logic
4. another idea?

None of them convince me 100%, but I think the clearest one is 1) since does not add special cases to the main logic: "We do not serve inactive versions". However, it's the one that requires more changes in the code 😞 . What do you think? Do you have some opinions here?

**Comment by ericholscher** [comment]
> None of them convince me 100%, but I think the clearest one is 1) since does not add special cases to the main logic: "We do not serve inactive versions". However, it's the one that requires more changes in the code 😞 . What do you think? Do you have some opinions here?


It seems like having the state of the PR in the Version model would be useful for a few UI elements, so that seems like a reasonable approach. I agree having fewer special cases and weird exceptions is good, and making it explicit what we're doing is better. 👍
