### ISSUE TITLE
Build failed: No module named 'sphinx_panels'

### ISSUE THREAD

**Issue by pamoroso** [readthedocs/readthedocs.org#9405]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/suite8080/
* Build URL (if applicable): https://readthedocs.org/projects/suite8080/builds/17347725/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/pamoroso/

## Expected Result

Successful build.

## Actual Result

The latest build of my project failed with the error:

```
Extension error:
Could not import extension sphinx_panels (exception: No module named 'sphinx_panels')
```

The previous successful build was over 3 months ago and, since then, I changed the repo only to add the new file `asm/twirl.asm` not directly tracked by Sphinx or its extensions the project relies on, such as `sphinx.ext.autodoc` and `sphinx.ext.napoleon`. I didn't change anything else in the documentation files.

I write the documentation with Jupyter Book, which uses Sphinx as a backend, and publish it to Read The Docs.

Is this an issue with Read The Docs, Sphinx, or Jupyter Book? Were there any related Read The Docs toolchain changes over the past few months?

**Comment by benjaoming** [comment]
Hi @pamoroso :wave: 

The immediate reason is that you would have to use `sphinx-design` instead of `sphinx-panels` in your `docs/conf.py`.

See: https://jupyterbook.org/en/stable/reference/_changelog.html?highlight=sphinx-panels#new-and-breaking

In addition to this, I would suggest that you pin the version of Jupyter-Book that you use, rather than `master.zip`. This means putting `jupyter-book==0.13` in your `requirements.txt`.

You can read more about reproducible builds and dependencies here:

https://docs.readthedocs.io/en/latest/guides/reproducible-builds.html#pinning-transitive-dependencies

Closing this issue as it doesn't have anything to do with Read the Docs :)

**Comment by humitos** [comment]
There is no need to have "conf.py" in the repository anymore. Read the Docs + Jupyter work great now that we added support for "build.jobs"

Take a look at the official documentation: https://jupyterbook.org/en/latest/publish/readthedocs.html

**Comment by benjaoming** [comment]
Me too, I would be happy to hear an answer to how changes are addressed in `conf.py` in the normal upgrade workflow for Jupyter Book. I'll be having a look at this shortly, as we're building an example project for Jupyter Book integration.

**Comment by pamoroso** [comment]
@humitos I'm trying to figure how to update my repo's configuration. But, after running `jupyter-book config sphinx path/to/docs`, Jupyter Book still generates a `conf.py` that references `sphinx_panels`. Replacing `sphinx_panels` with `sphinx_design` generates a module not found error.
