### ISSUE TITLE
Force-push a tag builds previous commit

### ISSUE THREAD

**Issue by kukushking** [readthedocs/readthedocs.org#9618]
## Details

* Build URL (if applicable): https://readthedocs.org/projects/aws-sdk-pandas/builds/18134030/

## Expected Result

Build the latest tagged commit

## Actual Result

The webhook started the build but it built from the old commit. I had to start the build manually to check out the latest changes

**Comment by stsewd** [comment]
I was able to replicate this, looks like the tag is updated after the checkout step. This is also a problem when forcing push a commit to that tag, since the previous commit won't be in the repository https://readthedocs.org/projects/test-builds/builds/18144846/, we should probably just use the name of the tag to do the checkout instead of the commit, but not sure if that would cause any other problems, but we also use the name of the branch for branches so I think it should be fine?

**Comment by humitos** [comment]
> we should probably just use the name of the tag to do the checkout instead of the commit, but not sure if that would cause any other problems, but we also use the name of the branch for branches so I think it should be fine?

Using the name of the tag makes sense to me.

**Comment by kukushking** [comment]
Makes sense to me too if you ask me 🙂

**Comment by humitos** [comment]
@kukushking we have refactored all the logic behind the Git clone/checkout steps. Can you confirm if this is still an issue for you? Any new information would be appreciated.

**Comment by kukushking** [comment]
Hi @humitos look all right to me. Thank you!

**Comment by humitos** [comment]
That's great! I will close the issue then. Please, reopen if you find it's happening again.
