### ISSUE TITLE
redirect stopped working?

### ISSUE THREAD

**Issue by afeld** [readthedocs/readthedocs.org#9705]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/python-coding-for-public-policy/
* Build URL (if applicable): n/a
* Read the Docs username n/a

## Expected Result

I have a couple redirects set up through the admin site:

<img width="638" alt="Screen Shot 2022-11-02 at 5 42 18 PM" src="https://user-images.githubusercontent.com/86842/199608106-7cb2ee54-1fa7-42a8-88bd-f98adbc73b5e.png">

The redirect from

https://python-public-policy.afeld.me/en/latest/

to

https://python-public-policy.afeld.me/en/latest/README.html

was working a week ago, but isn't anymore. Don't believe I've touched anything since.

## Actual Result

```
$ curl -I https://python-public-policy.afeld.me/en/latest/
HTTP/2 200
...
```

Thanks!

**Comment by stsewd** [comment]
Hi! Redirects work only if the page doesn't exist (404), since you added an index.md file https://github.com/afeld/python-public-policy/blob/main/index.md the redirect stopped working.  See https://docs.readthedocs.io/en/stable/user-defined-redirects.html#features.

If you still want to have the index.md file and do the redirect from RTD, we can enable the `forced redirect` feature, so the redirect works even if the page exists.

**Comment by afeld** [comment]
> See https://docs.readthedocs.io/en/stable/user-defined-redirects.html#features.

D'oh! Read The Docs, Aidan 🙃 

> we can enable the `forced redirect` feature

Sure, thanks!

**Comment by stsewd** [comment]
Done!

```
$ curl -I https://python-public-policy.afeld.me/en/latest/
HTTP/2 302 
date: Thu, 03 Nov 2022 17:57:17 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: https://python-public-policy.afeld.me/en/latest/README.html
```
