### ISSUE TITLE
Conditionally skipped builds are "pending" instead of "passed"

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9791]
PRs end up having the "pending" state although a build has been correctly and intentionally skipped.

Example:

![image](https://user-images.githubusercontent.com/374612/206479658-7bdcf10d-06cb-4107-8c58-32c75e9d132a.png)

![image](https://user-images.githubusercontent.com/374612/206515172-da26397d-797c-44c5-8dcf-9db5c4d32965.png)

![image](https://user-images.githubusercontent.com/374612/206515256-b2008337-3375-406a-b932-58e178cdb03b.png)

https://github.com/readthedocs/readthedocs.org/pull/9789
https://readthedocs.org/projects/dev/builds/18859457/

In another PR, the build wasn't skipped even though it seems to have contained no changes:

https://github.com/readthedocs/readthedocs.org/pull/9734

**Comment by humitos** [comment]
I've seen the same behavior lately, but I think it's related to some GitHub permission because every time a PR without changes in `docs/` is opened (the build is skipped) I got this notification in my dashboard:

![Screenshot_2022-12-08_19-40-58](https://user-images.githubusercontent.com/244656/206539904-6add59fd-1deb-479a-8d67-0d3c96e0bdbe.png)

**Comment by benjaoming** [comment]
We need to track the GitHub settings for "Required Builds" here.

The PR referred here https://github.com/readthedocs/readthedocs.org/pull/9788 will make it impossible to use required builds together with skipped builds AFAICT. The skipped builds will turn out yellow and the PR will never be merge-able.

**Comment by ericholscher** [comment]
I am debugging this now, and think I've found the issue.
