### ISSUE TITLE
Modifications to built HTML in a post_build job do not show up in the site preview

### ISSUE THREAD

**Issue by choldgraf** [readthedocs/readthedocs.org#9797]
## Details
I am experimenting with using [staticrypt](https://github.com/robinmoisson/staticrypt) to encrypt some HTML files that are built with Sphinx before being uploaded to RTD. To do so, I'm using a `post_build` event that modifies the built HTML and replaces it with an encrypted version. However, in the PR preview these changes do not seem to propagate.

For example:

- [Here is the `post_build` configuration I'm using to do the encrypting](https://github.com/2i2c-org/team-compass/pull/585/files#diff-cde814ef2f549dc093f5b8fc533b7e8f47e7b32a8081e0760e57d5c25a1139d9R12-R18)
- I also have a `cat` command at the end and, [in the build preview](https://readthedocs.org/projects/2i2c-team-compass/builds/18882794/), I confirm that the contents of the HTML are in-fact encrypted.
- However, [in the PR preview version of this page](https://2i2c-team-compass--585.org.readthedocs.build/en/585/hidden/test.html), it is viewable instead of being encrypted.

Project info:

* Read the Docs project URL: https://readthedocs.org/projects/2i2c-team-compass
* Build URL (if applicable): https://readthedocs.org/projects/2i2c-team-compass/builds/18882794/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/choldgraf

## Expected Result

I expected the page to be hidden behind a password, similar to other pages with `staticrypt`.

## Actual Result

The page is viewable to anyone.

**Comment by humitos** [comment]
Hi Chris! It seems that you are hitting this bug https://github.com/readthedocs/readthedocs.org/issues/9172 which will be solved by https://github.com/readthedocs/readthedocs.org/issues/9179

The problem here is that Read the Docs is moving the output of the build process immediately after `build` and before running `post_build`. That should not work like that.

I suggest you to subscribe to #9179 to get updates about this. That issue is already in our roadmap, so we plan to fix it in the following weeks/months.

I think this issue could be closed as duplicated.

**Comment by choldgraf** [comment]
Is this completed now? I see that this one is still open

- https://github.com/readthedocs/readthedocs.org/issues/9179

**Comment by humitos** [comment]
It's not complete, no. I'd assume that @stsewd closed this issue as duplicated of #9179, maybe? @stsewd can you confirm?

**Comment by choldgraf** [comment]
Ah I see - in case it is helpful, FYI you can close issues as `notplanned` / `duplicated` etc by clicking the drop-down arrow before clicking the close button:

![image](https://user-images.githubusercontent.com/1839645/208630759-76d5cab6-1d66-4123-b86f-5c9398657943.png)
