### ISSUE TITLE
Method display in search results

### ISSUE THREAD

**Issue by jamie-lemon** [readthedocs/readthedocs.org#9871]
## Details

When documenting methods using this kind of markup:

.. method:: myMethodName()

From the built docs I can search and find the method no problem in the search field, however the search results page always says "Python method ..." in the listing. In my case I am not always documenting Python methods!

## Expected Result

I would just like the search results to say "Method ..."

## Actual Result

"Python method ...." displays.

**Comment by humitos** [comment]
Hi. Can you provide an URL with an example showing this case? Thanks

**Comment by jamie-lemon** [comment]
Sure: 
https://smartoffice.readthedocs.io/en/latest/search.html?q=setSelectionIsBold&check_keywords=yes&area=default#

Actually this is slightly different to my local build version, probably to do with my installed version of Sphinx, there is says **Python method ...** here is says **[py:method]**.

**Comment by humitos** [comment]
@jamie-lemon I'm not able to see the source code (rST) of the resulting page. Are you using a private repository?

**Comment by jamie-lemon** [comment]
The repo is here: git://git.ghostscript.com/smartoffice-docs.git

**Comment by stsewd** [comment]
Hi @jamie-lemon 

> Actually this is slightly different to my local build version, probably to do with my installed version of Sphinx, there is says Python method ... here is says [py:method].

That's because on RTD, we override the search to use our server side search (https://docs.readthedocs.io/en/stable/server-side-search/index.html). I don't think it's possible to change `Python method` to just `Method` from sphinx, but you could do it using our API, but you'll need to do that by manually calling our search API and when displaying results just use `method` instead of `py:method`. Maybe you could also use JS to remote that from results.


https://github.com/readthedocs/readthedocs.org-ghsa-7fcx-wwr3-99jv/blob/96a4ab71fd51f54422c0d5586c71d1057b7cc8d2/readthedocs/core/static-src/core/js/doc-embed/search.js#L171-L171
