### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:  self-signed certificate (_ssl.c:997)')))

### ISSUE THREAD

**Issue by pilgrimage80** [readthedocs/readthedocs.org#9924]
Hello, as a result of long efforts, I am very close to integrating gitlab and readthedocs with each other. However, when I log in with Sign in with GitLab from devthedocs.org, which I set up locally, it redirects to local gitlab but gives the following certificate error. I need to trust the two sites to each other through the certificate, I am also investigating this, but I would like to ask you for help in the hope that I can solve it faster, I would appreciate it if you help me how to do this that you are experienced in this subject. Humitos please don't copy and paste your philosophy I have read your philosophy and I respect it but I need some help. I hope you can take the time to answer this question and help me with your philosophy. Please, I would be very grateful if one of you could answer this question. It should not be so difficult to help each other here.

An error occurred while attempting to login via your social network account.

HTTPSConnectionPool(host='gitlab.tutel', port=443): Max retries exceeded with url: /oauth/token 
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: 
self-signed certificate (_ssl.c:997)')))

**Comment by benjaoming** [comment]
Thank you for opening an issue in our repository.

However, since your question refers to a custom installation and tools related to that, we kindly refer you to other channels:

* Get support on Stack Overflow, using "read-the-docs" tag or another tag that's relevant to your issue: https://stackoverflow.com/questions/tagged/read-the-docs
* List of topics that we DO NOT support: https://docs.readthedocs.io/en/stable/open-source-philosophy.html#unsupported

_Note 1:_ I observed that other team members have consistently told you that we are not supporting custom installations of Read the Docs at your company. Yet, you continue to open up support issues on this topic in our channels. It seems that you have chosen to ignore these messages, so I'm simply going to lock this thread.

_Note 2:_ With the nature of your question in mind, I would also warn against an intention of running an on-prem Read the Docs without sufficient knowledge or experience in cloud engineering. If you do not understand the above SSL issue, I think you will find too many challenges in the project that you've undertaken.
